// Code generated by goctl. DO NOT EDIT.
// Source: phonecall.proto

package phonecall_client

import (
	"context"

	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/service/biz/phone_call/phonecall"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PhoneCallSession             = phonecall.PhoneCallSession
	TLMakePhoneCallSession       = phonecall.TLMakePhoneCallSession
	TLMakePhoneCallSessionByLoad = phonecall.TLMakePhoneCallSessionByLoad
	TLSetGB                      = phonecall.TLSetGB
	Void                         = phonecall.Void

	PhonecallClient interface {
		SetGB(ctx context.Context, in *TLSetGB, opts ...grpc.CallOption) (*Void, error)
		MakePhoneCallSession(ctx context.Context, in *TLMakePhoneCallSession, opts ...grpc.CallOption) (*PhoneCallSession, error)
		MakePhoneCallSessionByLoad(ctx context.Context, in *TLMakePhoneCallSessionByLoad, opts ...grpc.CallOption) (*PhoneCallSession, error)
	}

	defaultPhonecallClient struct {
		cli zrpc.Client
	}
)

func NewPhonecallClient(cli zrpc.Client) PhonecallClient {
	return &defaultPhonecallClient{
		cli: cli,
	}
}

func (m *defaultPhonecallClient) SetGB(ctx context.Context, in *TLSetGB, opts ...grpc.CallOption) (*Void, error) {
	client := phonecall.NewRPCPhoneCallClient(m.cli.Conn())
	return client.SetGB(ctx, in, opts...)
}

func (m *defaultPhonecallClient) MakePhoneCallSession(ctx context.Context, in *TLMakePhoneCallSession, opts ...grpc.CallOption) (*PhoneCallSession, error) {
	client := phonecall.NewRPCPhoneCallClient(m.cli.Conn())
	return client.MakePhoneCallSession(ctx, in, opts...)
}

func (m *defaultPhonecallClient) MakePhoneCallSessionByLoad(ctx context.Context, in *TLMakePhoneCallSessionByLoad, opts ...grpc.CallOption) (*PhoneCallSession, error) {
	client := phonecall.NewRPCPhoneCallClient(m.cli.Conn())
	return client.MakePhoneCallSessionByLoad(ctx, in, opts...)
}
