// Code generated by goctl. DO NOT EDIT.
// Source: mtproto.proto

package service

import (
	"context"

	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/mtproto"
	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/bff/channels/internal/core"
)

func (s *Service) ChannelsReadHistory(ctx context.Context, in *mtproto.TLChannelsReadHistory) (*mtproto.Bool, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsReadHistory - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsReadHistory(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsReadHistory - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsDeleteMessages(ctx context.Context, in *mtproto.TLChannelsDeleteMessages) (*mtproto.Messages_AffectedMessages, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsDeleteMessages - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsDeleteMessages(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsDeleteMessages - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetMessages(ctx context.Context, in *mtproto.TLChannelsGetMessages) (*mtproto.Messages_Messages, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetMessages - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetMessages(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetMessages - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetParticipants(ctx context.Context, in *mtproto.TLChannelsGetParticipants) (*mtproto.Channels_ChannelParticipants, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetParticipants - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetParticipants(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetParticipants - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetParticipant(ctx context.Context, in *mtproto.TLChannelsGetParticipant) (*mtproto.Channels_ChannelParticipant, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetParticipant - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetParticipant(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetParticipant - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetChannels(ctx context.Context, in *mtproto.TLChannelsGetChannels) (*mtproto.Messages_Chats, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetChannels - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetChannels(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetChannels - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetFullChannel(ctx context.Context, in *mtproto.TLChannelsGetFullChannel) (*mtproto.Messages_ChatFull, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetFullChannel - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetFullChannel(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetFullChannel - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsCreateChannel(ctx context.Context, in *mtproto.TLChannelsCreateChannel) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsCreateChannel - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsCreateChannel(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsCreateChannel - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsEditAdmin(ctx context.Context, in *mtproto.TLChannelsEditAdmin) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsEditAdmin - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsEditAdmin(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsEditAdmin - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsEditTitle(ctx context.Context, in *mtproto.TLChannelsEditTitle) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsEditTitle - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsEditTitle(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsEditTitle - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsEditPhoto(ctx context.Context, in *mtproto.TLChannelsEditPhoto) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsEditPhoto - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsEditPhoto(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsEditPhoto - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsJoinChannel(ctx context.Context, in *mtproto.TLChannelsJoinChannel) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsJoinChannel - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsJoinChannel(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsJoinChannel - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsLeaveChannel(ctx context.Context, in *mtproto.TLChannelsLeaveChannel) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsLeaveChannel - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsLeaveChannel(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsLeaveChannel - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsInviteToChannel(ctx context.Context, in *mtproto.TLChannelsInviteToChannel) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsInviteToChannel - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsInviteToChannel(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsInviteToChannel - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsDeleteChannel(ctx context.Context, in *mtproto.TLChannelsDeleteChannel) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsDeleteChannel - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsDeleteChannel(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsDeleteChannel - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsExportMessageLink(ctx context.Context, in *mtproto.TLChannelsExportMessageLink) (*mtproto.ExportedMessageLink, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsExportMessageLink - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsExportMessageLink(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsExportMessageLink - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsToggleSignatures(ctx context.Context, in *mtproto.TLChannelsToggleSignatures) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsToggleSignatures - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsToggleSignatures(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsToggleSignatures - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetAdminedPublicChannels(ctx context.Context, in *mtproto.TLChannelsGetAdminedPublicChannels) (*mtproto.Messages_Chats, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetAdminedPublicChannels - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetAdminedPublicChannels(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetAdminedPublicChannels - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsEditBanned(ctx context.Context, in *mtproto.TLChannelsEditBanned) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsEditBanned - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsEditBanned(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsEditBanned - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetAdminLog(ctx context.Context, in *mtproto.TLChannelsGetAdminLog) (*mtproto.Channels_AdminLogResults, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetAdminLog - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetAdminLog(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetAdminLog - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsSetStickers(ctx context.Context, in *mtproto.TLChannelsSetStickers) (*mtproto.Bool, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsSetStickers - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsSetStickers(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsSetStickers - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsReadMessageContents(ctx context.Context, in *mtproto.TLChannelsReadMessageContents) (*mtproto.Bool, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsReadMessageContents - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsReadMessageContents(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsReadMessageContents - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsDeleteHistory9BAA9647(ctx context.Context, in *mtproto.TLChannelsDeleteHistory9BAA9647) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsDeleteHistory9BAA9647 - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsDeleteHistory9BAA9647(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsDeleteHistory9BAA9647 - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsTogglePreHistoryHidden(ctx context.Context, in *mtproto.TLChannelsTogglePreHistoryHidden) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsTogglePreHistoryHidden - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsTogglePreHistoryHidden(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsTogglePreHistoryHidden - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetGroupsForDiscussion(ctx context.Context, in *mtproto.TLChannelsGetGroupsForDiscussion) (*mtproto.Messages_Chats, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetGroupsForDiscussion - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetGroupsForDiscussion(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetGroupsForDiscussion - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsSetDiscussionGroup(ctx context.Context, in *mtproto.TLChannelsSetDiscussionGroup) (*mtproto.Bool, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsSetDiscussionGroup - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsSetDiscussionGroup(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsSetDiscussionGroup - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsEditCreator(ctx context.Context, in *mtproto.TLChannelsEditCreator) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsEditCreator - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsEditCreator(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsEditCreator - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsEditLocation(ctx context.Context, in *mtproto.TLChannelsEditLocation) (*mtproto.Bool, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsEditLocation - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsEditLocation(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsEditLocation - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsToggleSlowMode(ctx context.Context, in *mtproto.TLChannelsToggleSlowMode) (*mtproto.Updates, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsToggleSlowMode - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsToggleSlowMode(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsToggleSlowMode - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsGetInactiveChannels(ctx context.Context, in *mtproto.TLChannelsGetInactiveChannels) (*mtproto.Messages_InactiveChats, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsGetInactiveChannels - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsGetInactiveChannels(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsGetInactiveChannels - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsDeleteParticipantHistory(ctx context.Context, in *mtproto.TLChannelsDeleteParticipantHistory) (*mtproto.Messages_AffectedHistory, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsDeleteParticipantHistory - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsDeleteParticipantHistory(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsDeleteParticipantHistory - reply: %+v", r)
	return r, err
}

func (s *Service) ChannelsDeleteHistoryAF369D42(ctx context.Context, in *mtproto.TLChannelsDeleteHistoryAF369D42) (*mtproto.Bool, error) {
	c := core.NewChannels(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.ChannelsDeleteHistoryAF369D42 - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.ChannelsDeleteHistoryAF369D42(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.ChannelsDeleteHistoryAF369D42 - reply: %+v", r)
	return r, err
}
