// Code generated by goctl. DO NOT EDIT.
// Source: account.proto

package service

import (
	"context"
	"encoding/json"

	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/bff/account_customize/internal/core"
)

func (s *Service) AccountDelete(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_delete - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountDelete(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_delete - reply: %+v", r)
	return r, err
}

func (s *Service) AccountChangePassword(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_changePassword - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountChangePassword(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_changePassword - reply: %+v", r)
	return r, err
}

func (s *Service) AccountChangeEmail(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_changeEmail - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountChangeEmail(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_changeEmail - reply: %+v", r)
	return r, err
}

func (s *Service) AccountChangeProfile(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_changeProfile - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountChangeProfile(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_changeProfile - reply: %+v", r)
	return r, err
}

func (s *Service) AccountForgotPassword(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_forgotPassword - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountForgotPassword(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_forgotPassword - reply: %+v", r)
	return r, err
}

func (s *Service) AccountConfirmationSend(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_confirmationSend - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountConfirmationSend(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_confirmationSend - reply: %+v", r)
	return r, err
}

func (s *Service) AccountConfirmationConfirm(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccount(ctx, s.svcCtx)

	c.Logger.Debugf("account.account_confirmationConfirm - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountConfirmationConfirm(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("account.account_confirmationConfirm - reply: %+v", r)
	return r, err
}
