// Code generated by goctl. DO NOT EDIT.
// Source: mtproto.proto

package service

import (
	"context"
	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/mtproto"

	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/bff/voipcalls/internal/core"
)

func (s *Service) MessagesDeletePhoneCallHistory(ctx context.Context, in *mtproto.TLMessagesDeletePhoneCallHistory) (*mtproto.Messages_AffectedFoundMessages, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.MessagesDeletePhoneCallHistory - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.MessagesDeletePhoneCallHistory(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.MessagesDeletePhoneCallHistory - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneGetCallConfig(ctx context.Context, in *mtproto.TLPhoneGetCallConfig) (*mtproto.DataJSON, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneGetCallConfig - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneGetCallConfig(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneGetCallConfig - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneRequestCall(ctx context.Context, in *mtproto.TLPhoneRequestCall) (*mtproto.Phone_PhoneCall, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneRequestCall - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneRequestCall(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneRequestCall - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneAcceptCall(ctx context.Context, in *mtproto.TLPhoneAcceptCall) (*mtproto.Phone_PhoneCall, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneAcceptCall - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneAcceptCall(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneAcceptCall - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneConfirmCall(ctx context.Context, in *mtproto.TLPhoneConfirmCall) (*mtproto.Phone_PhoneCall, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneConfirmCall - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneConfirmCall(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneConfirmCall - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneReceivedCall(ctx context.Context, in *mtproto.TLPhoneReceivedCall) (*mtproto.Bool, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneReceivedCall - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneReceivedCall(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneReceivedCall - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneDiscardCall(ctx context.Context, in *mtproto.TLPhoneDiscardCall) (*mtproto.Updates, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneDiscardCall - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneDiscardCall(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneDiscardCall - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneSetCallRating(ctx context.Context, in *mtproto.TLPhoneSetCallRating) (*mtproto.Updates, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneSetCallRating - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneSetCallRating(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneSetCallRating - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneSaveCallDebug(ctx context.Context, in *mtproto.TLPhoneSaveCallDebug) (*mtproto.Bool, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneSaveCallDebug - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneSaveCallDebug(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneSaveCallDebug - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneSendSignalingData(ctx context.Context, in *mtproto.TLPhoneSendSignalingData) (*mtproto.Bool, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneSendSignalingData - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneSendSignalingData(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneSendSignalingData - reply: %+v", r)
	return r, err
}

func (s *Service) PhoneSaveCallLog(ctx context.Context, in *mtproto.TLPhoneSaveCallLog) (*mtproto.Bool, error) {
	c := core.NewVoipcalls(ctx, s.svcCtx)

	c.Logger.Debugf("mtproto.PhoneSaveCallLog - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.PhoneSaveCallLog(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("mtproto.PhoneSaveCallLog - reply: %+v", r)
	return r, err
}
