// Code generated by goctl. DO NOT EDIT.
// Source: accounts.proto

package service

import (
	"context"
	"encoding/json"

	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/bff/accounts/internal/core"
)

func (s *Service) AccountsDelete(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_delete - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountsDelete(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_delete - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsChangePassword(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_changePassword - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountsChangePassword(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_changePassword - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsChangeEmail(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_changeEmail - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountsChangeEmail(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_changeEmail - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsChangeProfile(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_changeProfile - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountsChangeProfile(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_changeProfile - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsForgotPassword(ctx context.Context, in json.RawMessage) (interface{}, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_forgotPassword - metadata: %s, request: %s", c.MD.DebugString(), string(in))
	r, err := c.AccountsForgotPassword(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_forgotPassword - reply: %+v", r)
	return r, err
}
