create table countries_flags
(
    id   bigint unsigned auto_increment
        primary key,
    code varchar(4)   not null,
    name varchar(45)  not null,
    flag varchar(128) not null
);

INSERT INTO countries_flags (id, code, name, flag) VALUES (1, 'AFG', 'Afghanistan', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (2, 'ALB', 'Albania', 'https://flagcdn.com/w320/al.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (3, 'DZA', 'Algeria', 'https://flagcdn.com/w320/dz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (4, 'ASM', 'American Samoa', 'https://flagcdn.com/w320/as.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (5, 'AND', 'Andorra', 'https://flagcdn.com/w320/ad.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (6, 'AGO', 'Angola', 'https://flagcdn.com/w320/ao.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (7, 'AIA', 'Anguilla', 'https://flagcdn.com/w320/ai.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (8, 'ATA', 'Antarctica', 'https://flagcdn.com/w320/aq.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (9, 'ATG', 'Antigua and Barbuda', 'https://flagcdn.com/w320/ag.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (10, 'ARG', 'Argentina', 'https://flagcdn.com/w320/ar.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (11, 'ARM', 'Armenia', 'https://flagcdn.com/w320/am.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (12, 'ABW', 'Aruba', 'https://flagcdn.com/w320/aw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (13, 'AUS', 'Australia', 'https://flagcdn.com/w320/au.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (14, 'AUT', 'Austria', 'https://flagcdn.com/w320/at.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (15, 'AZE', 'Azerbaijan', 'https://flagcdn.com/w320/az.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (16, 'BHS', 'Bahamas', 'https://flagcdn.com/w320/bs.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (17, 'BHR', 'Bahrain', 'https://flagcdn.com/w320/bh.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (18, 'BGD', 'Bangladesh', 'https://flagcdn.com/w320/bd.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (19, 'BRB', 'Barbados', 'https://flagcdn.com/w320/bb.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (20, 'BLR', 'Belarus', 'https://flagcdn.com/w320/by.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (21, 'BEL', 'Belgium', 'https://flagcdn.com/w320/be.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (22, 'BLZ', 'Belize', 'https://flagcdn.com/w320/bz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (23, 'BEN', 'Benin', 'https://flagcdn.com/w320/bj.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (24, 'BMU', 'Bermuda', 'https://flagcdn.com/w320/bm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (25, 'BTN', 'Bhutan', 'https://flagcdn.com/w320/bt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (26, 'BOL', 'Bolivia', 'https://flagcdn.com/w320/bo.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (27, 'BIH', 'Bosnia and Herzegovina', 'https://flagcdn.com/w320/ba.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (28, 'BWA', 'Botswana', 'https://flagcdn.com/w320/bw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (29, 'BVT', 'Bouvet Island', 'https://flagcdn.com/w320/bv.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (30, 'BRA', 'Brazil', 'https://flagcdn.com/w320/br.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (31, 'IOT', 'British Indian Ocean Territory', 'https://flagcdn.com/w320/io.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (32, 'VGB', 'British Virgin Islands', 'https://flagcdn.com/w320/vg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (33, 'BRN', 'Brunei', 'https://flagcdn.com/w320/bn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (34, 'BGR', 'Bulgaria', 'https://flagcdn.com/w320/bg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (35, 'BFA', 'Burkina Faso', 'https://flagcdn.com/w320/bf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (36, 'BDI', 'Burundi', 'https://flagcdn.com/w320/bi.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (37, 'KHM', 'Cambodia', 'https://flagcdn.com/w320/kh.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (38, 'CMR', 'Cameroon', 'https://flagcdn.com/w320/cm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (39, 'CAN', 'Canada', 'https://flagcdn.com/w320/ca.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (40, 'CPV', 'Cape Verde', 'https://flagcdn.com/w320/cv.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (41, 'BES', 'Caribbean Netherlands', 'https://flagcdn.com/w320/bq.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (42, 'CYM', 'Cayman Islands', 'https://flagcdn.com/w320/ky.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (43, 'CAF', 'Central African Republic', 'https://flagcdn.com/w320/cf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (44, 'TCD', 'Chad', 'https://flagcdn.com/w320/td.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (45, 'CHL', 'Chile', 'https://flagcdn.com/w320/cl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (46, 'CHN', 'China', 'https://flagcdn.com/w320/cn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (47, 'CXR', 'Christmas Island', 'https://flagcdn.com/w320/cx.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (48, 'CCK', 'Cocos (Keeling) Islands', 'https://flagcdn.com/w320/cc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (49, 'COL', 'Colombia', 'https://flagcdn.com/w320/co.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (50, 'COM', 'Comoros', 'https://flagcdn.com/w320/km.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (51, 'COK', 'Cook Islands', 'https://flagcdn.com/w320/ck.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (52, 'CRI', 'Costa Rica', 'https://flagcdn.com/w320/cr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (53, 'HRV', 'Croatia', 'https://flagcdn.com/w320/hr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (54, 'CUB', 'Cuba', 'https://flagcdn.com/w320/cu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (55, 'CUW', 'Curaçao', 'https://flagcdn.com/w320/cw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (56, 'CYP', 'Cyprus', 'https://flagcdn.com/w320/cy.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (57, 'CZE', 'Czechia', 'https://flagcdn.com/w320/cz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (58, 'COD', 'DR Congo', 'https://flagcdn.com/w320/cd.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (59, 'DNK', 'Denmark', 'https://flagcdn.com/w320/dk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (60, 'DJI', 'Djibouti', 'https://flagcdn.com/w320/dj.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (61, 'DMA', 'Dominica', 'https://flagcdn.com/w320/dm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (62, 'DOM', 'Dominican Republic', 'https://flagcdn.com/w320/do.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (63, 'ECU', 'Ecuador', 'https://flagcdn.com/w320/ec.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (64, 'EGY', 'Egypt', 'https://flagcdn.com/w320/eg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (65, 'SLV', 'El Salvador', 'https://flagcdn.com/w320/sv.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (66, 'GNQ', 'Equatorial Guinea', 'https://flagcdn.com/w320/gq.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (67, 'ERI', 'Eritrea', 'https://flagcdn.com/w320/er.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (68, 'EST', 'Estonia', 'https://flagcdn.com/w320/ee.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (69, 'SWZ', 'Eswatini', 'https://flagcdn.com/w320/sz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (70, 'ETH', 'Ethiopia', 'https://flagcdn.com/w320/et.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (71, 'FLK', 'Falkland Islands', 'https://flagcdn.com/w320/fk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (72, 'FRO', 'Faroe Islands', 'https://flagcdn.com/w320/fo.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (73, 'FJI', 'Fiji', 'https://flagcdn.com/w320/fj.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (74, 'FIN', 'Finland', 'https://flagcdn.com/w320/fi.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (75, 'FRA', 'France', 'https://flagcdn.com/w320/fr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (76, 'GUF', 'French Guiana', 'https://flagcdn.com/w320/gf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (77, 'PYF', 'French Polynesia', 'https://flagcdn.com/w320/pf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (78, 'ATF', 'French Southern and Antarctic Lands', 'https://flagcdn.com/w320/tf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (79, 'GAB', 'Gabon', 'https://flagcdn.com/w320/ga.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (80, 'GMB', 'Gambia', 'https://flagcdn.com/w320/gm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (81, 'GEO', 'Georgia', 'https://flagcdn.com/w320/ge.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (82, 'DEU', 'Germany', 'https://flagcdn.com/w320/de.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (83, 'GHA', 'Ghana', 'https://flagcdn.com/w320/gh.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (84, 'GIB', 'Gibraltar', 'https://flagcdn.com/w320/gi.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (85, 'GRC', 'Greece', 'https://flagcdn.com/w320/gr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (86, 'GRL', 'Greenland', 'https://flagcdn.com/w320/gl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (87, 'GRD', 'Grenada', 'https://flagcdn.com/w320/gd.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (88, 'GLP', 'Guadeloupe', 'https://flagcdn.com/w320/gp.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (89, 'GUM', 'Guam', 'https://flagcdn.com/w320/gu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (90, 'GTM', 'Guatemala', 'https://flagcdn.com/w320/gt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (91, 'GGY', 'Guernsey', 'https://flagcdn.com/w320/gg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (92, 'GIN', 'Guinea', 'https://flagcdn.com/w320/gn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (93, 'GNB', 'Guinea-Bissau', 'https://flagcdn.com/w320/gw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (94, 'GUY', 'Guyana', 'https://flagcdn.com/w320/gy.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (95, 'HTI', 'Haiti', 'https://flagcdn.com/w320/ht.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (96, 'HMD', 'Heard Island and McDonald Islands', 'https://flagcdn.com/w320/hm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (97, 'HND', 'Honduras', 'https://flagcdn.com/w320/hn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (98, 'HKG', 'Hong Kong', 'https://flagcdn.com/w320/hk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (99, 'HUN', 'Hungary', 'https://flagcdn.com/w320/hu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (100, 'ISL', 'Iceland', 'https://flagcdn.com/w320/is.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (101, 'IND', 'India', 'https://flagcdn.com/w320/in.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (102, 'IDN', 'Indonesia', 'https://flagcdn.com/w320/id.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (103, 'IRN', 'Iran', 'https://flagcdn.com/w320/ir.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (104, 'IRQ', 'Iraq', 'https://flagcdn.com/w320/iq.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (105, 'IRL', 'Ireland', 'https://flagcdn.com/w320/ie.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (106, 'IMN', 'Isle of Man', 'https://flagcdn.com/w320/im.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (107, 'ISR', 'Israel', 'https://flagcdn.com/w320/il.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (108, 'ITA', 'Italy', 'https://flagcdn.com/w320/it.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (109, 'CIV', 'Ivory Coast', 'https://flagcdn.com/w320/ci.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (110, 'JAM', 'Jamaica', 'https://flagcdn.com/w320/jm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (111, 'JPN', 'Japan', 'https://flagcdn.com/w320/jp.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (112, 'JEY', 'Jersey', 'https://flagcdn.com/w320/je.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (113, 'JOR', 'Jordan', 'https://flagcdn.com/w320/jo.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (114, 'KAZ', 'Kazakhstan', 'https://flagcdn.com/w320/kz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (115, 'KEN', 'Kenya', 'https://flagcdn.com/w320/ke.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (116, 'KIR', 'Kiribati', 'https://flagcdn.com/w320/ki.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (117, 'UNK', 'Kosovo', 'https://flagcdn.com/w320/xk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (118, 'KWT', 'Kuwait', 'https://flagcdn.com/w320/kw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (119, 'KGZ', 'Kyrgyzstan', 'https://flagcdn.com/w320/kg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (120, 'LAO', 'Laos', 'https://flagcdn.com/w320/la.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (121, 'LVA', 'Latvia', 'https://flagcdn.com/w320/lv.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (122, 'LBN', 'Lebanon', 'https://flagcdn.com/w320/lb.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (123, 'LSO', 'Lesotho', 'https://flagcdn.com/w320/ls.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (124, 'LBR', 'Liberia', 'https://flagcdn.com/w320/lr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (125, 'LBY', 'Libya', 'https://flagcdn.com/w320/ly.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (126, 'LIE', 'Liechtenstein', 'https://flagcdn.com/w320/li.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (127, 'LTU', 'Lithuania', 'https://flagcdn.com/w320/lt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (128, 'LUX', 'Luxembourg', 'https://flagcdn.com/w320/lu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (129, 'MAC', 'Macau', 'https://flagcdn.com/w320/mo.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (130, 'MDG', 'Madagascar', 'https://flagcdn.com/w320/mg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (131, 'MWI', 'Malawi', 'https://flagcdn.com/w320/mw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (132, 'MYS', 'Malaysia', 'https://flagcdn.com/w320/my.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (133, 'MDV', 'Maldives', 'https://flagcdn.com/w320/mv.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (134, 'MLI', 'Mali', 'https://flagcdn.com/w320/ml.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (135, 'MLT', 'Malta', 'https://flagcdn.com/w320/mt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (136, 'MHL', 'Marshall Islands', 'https://flagcdn.com/w320/mh.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (137, 'MTQ', 'Martinique', 'https://flagcdn.com/w320/mq.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (138, 'MRT', 'Mauritania', 'https://flagcdn.com/w320/mr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (139, 'MUS', 'Mauritius', 'https://flagcdn.com/w320/mu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (140, 'MYT', 'Mayotte', 'https://flagcdn.com/w320/yt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (141, 'MEX', 'Mexico', 'https://flagcdn.com/w320/mx.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (142, 'FSM', 'Micronesia', 'https://flagcdn.com/w320/fm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (143, 'MDA', 'Moldova', 'https://flagcdn.com/w320/md.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (144, 'MCO', 'Monaco', 'https://flagcdn.com/w320/mc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (145, 'MNG', 'Mongolia', 'https://flagcdn.com/w320/mn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (146, 'MNE', 'Montenegro', 'https://flagcdn.com/w320/me.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (147, 'MSR', 'Montserrat', 'https://flagcdn.com/w320/ms.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (148, 'MAR', 'Morocco', 'https://flagcdn.com/w320/ma.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (149, 'MOZ', 'Mozambique', 'https://flagcdn.com/w320/mz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (150, 'MMR', 'Myanmar', 'https://flagcdn.com/w320/mm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (151, 'NAM', 'Namibia', 'https://flagcdn.com/w320/na.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (152, 'NRU', 'Nauru', 'https://flagcdn.com/w320/nr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (153, 'NPL', 'Nepal', 'https://flagcdn.com/w320/np.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (154, 'NLD', 'Netherlands', 'https://flagcdn.com/w320/nl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (155, 'NCL', 'New Caledonia', 'https://flagcdn.com/w320/nc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (156, 'NZL', 'New Zealand', 'https://flagcdn.com/w320/nz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (157, 'NIC', 'Nicaragua', 'https://flagcdn.com/w320/ni.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (158, 'NER', 'Niger', 'https://flagcdn.com/w320/ne.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (159, 'NGA', 'Nigeria', 'https://flagcdn.com/w320/ng.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (160, 'NIU', 'Niue', 'https://flagcdn.com/w320/nu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (161, 'NFK', 'Norfolk Island', 'https://flagcdn.com/w320/nf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (162, 'PRK', 'North Korea', 'https://flagcdn.com/w320/kp.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (163, 'MKD', 'North Macedonia', 'https://flagcdn.com/w320/mk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (164, 'MNP', 'Northern Mariana Islands', 'https://flagcdn.com/w320/mp.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (165, 'NOR', 'Norway', 'https://flagcdn.com/w320/no.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (166, 'OMN', 'Oman', 'https://flagcdn.com/w320/om.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (167, 'PAK', 'Pakistan', 'https://flagcdn.com/w320/pk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (168, 'PLW', 'Palau', 'https://flagcdn.com/w320/pw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (169, 'PSE', 'Palestine', 'https://flagcdn.com/w320/ps.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (170, 'PAN', 'Panama', 'https://flagcdn.com/w320/pa.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (171, 'PNG', 'Papua New Guinea', 'https://flagcdn.com/w320/pg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (172, 'PRY', 'Paraguay', 'https://flagcdn.com/w320/py.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (173, 'PER', 'Peru', 'https://flagcdn.com/w320/pe.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (174, 'PHL', 'Philippines', 'https://flagcdn.com/w320/ph.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (175, 'PCN', 'Pitcairn Islands', 'https://flagcdn.com/w320/pn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (176, 'POL', 'Poland', 'https://flagcdn.com/w320/pl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (177, 'PRT', 'Portugal', 'https://flagcdn.com/w320/pt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (178, 'PRI', 'Puerto Rico', 'https://flagcdn.com/w320/pr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (179, 'QAT', 'Qatar', 'https://flagcdn.com/w320/qa.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (180, 'COG', 'Republic of the Congo', 'https://flagcdn.com/w320/cg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (181, 'ROU', 'Romania', 'https://flagcdn.com/w320/ro.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (182, 'RUS', 'Russia', 'https://flagcdn.com/w320/ru.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (183, 'RWA', 'Rwanda', 'https://flagcdn.com/w320/rw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (184, 'REU', 'Réunion', 'https://flagcdn.com/w320/re.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (185, 'BLM', 'Saint Barthélemy', 'https://flagcdn.com/w320/bl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (186, 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'https://flagcdn.com/w320/sh.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (187, 'KNA', 'Saint Kitts and Nevis', 'https://flagcdn.com/w320/kn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (188, 'LCA', 'Saint Lucia', 'https://flagcdn.com/w320/lc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (189, 'MAF', 'Saint Martin', 'https://flagcdn.com/w320/mf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (190, 'SPM', 'Saint Pierre and Miquelon', 'https://flagcdn.com/w320/pm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (191, 'VCT', 'Saint Vincent and the Grenadines', 'https://flagcdn.com/w320/vc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (192, 'WSM', 'Samoa', 'https://flagcdn.com/w320/ws.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (193, 'SMR', 'San Marino', 'https://flagcdn.com/w320/sm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (194, 'SAU', 'Saudi Arabia', 'https://flagcdn.com/w320/sa.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (195, 'SEN', 'Senegal', 'https://flagcdn.com/w320/sn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (196, 'SRB', 'Serbia', 'https://flagcdn.com/w320/rs.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (197, 'SYC', 'Seychelles', 'https://flagcdn.com/w320/sc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (198, 'SLE', 'Sierra Leone', 'https://flagcdn.com/w320/sl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (199, 'SGP', 'Singapore', 'https://flagcdn.com/w320/sg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (200, 'SXM', 'Sint Maarten', 'https://flagcdn.com/w320/sx.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (201, 'SVK', 'Slovakia', 'https://flagcdn.com/w320/sk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (202, 'SVN', 'Slovenia', 'https://flagcdn.com/w320/si.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (203, 'SLB', 'Solomon Islands', 'https://flagcdn.com/w320/sb.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (204, 'SOM', 'Somalia', 'https://flagcdn.com/w320/so.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (205, 'ZAF', 'South Africa', 'https://flagcdn.com/w320/za.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (206, 'SGS', 'South Georgia', 'https://flagcdn.com/w320/gs.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (207, 'KOR', 'South Korea', 'https://flagcdn.com/w320/kr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (208, 'SSD', 'South Sudan', 'https://flagcdn.com/w320/ss.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (209, 'ESP', 'Spain', 'https://flagcdn.com/w320/es.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (210, 'LKA', 'Sri Lanka', 'https://flagcdn.com/w320/lk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (211, 'SDN', 'Sudan', 'https://flagcdn.com/w320/sd.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (212, 'SUR', 'Suriname', 'https://flagcdn.com/w320/sr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (213, 'SJM', 'Svalbard and Jan Mayen', 'https://flagcdn.com/w320/sj.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (214, 'SWE', 'Sweden', 'https://flagcdn.com/w320/se.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (215, 'CHE', 'Switzerland', 'https://flagcdn.com/w320/ch.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (216, 'SYR', 'Syria', 'https://flagcdn.com/w320/sy.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (217, 'STP', 'São Tomé and Príncipe', 'https://flagcdn.com/w320/st.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (218, 'TWN', 'Taiwan', 'https://flagcdn.com/w320/tw.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (219, 'TJK', 'Tajikistan', 'https://flagcdn.com/w320/tj.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (220, 'TZA', 'Tanzania', 'https://flagcdn.com/w320/tz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (221, 'THA', 'Thailand', 'https://flagcdn.com/w320/th.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (222, 'TLS', 'Timor-Leste', 'https://flagcdn.com/w320/tl.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (223, 'TGO', 'Togo', 'https://flagcdn.com/w320/tg.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (224, 'TKL', 'Tokelau', 'https://flagcdn.com/w320/tk.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (225, 'TON', 'Tonga', 'https://flagcdn.com/w320/to.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (226, 'TTO', 'Trinidad and Tobago', 'https://flagcdn.com/w320/tt.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (227, 'TUN', 'Tunisia', 'https://flagcdn.com/w320/tn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (228, 'TUR', 'Turkey', 'https://flagcdn.com/w320/tr.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (229, 'TKM', 'Turkmenistan', 'https://flagcdn.com/w320/tm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (230, 'TCA', 'Turks and Caicos Islands', 'https://flagcdn.com/w320/tc.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (231, 'TUV', 'Tuvalu', 'https://flagcdn.com/w320/tv.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (232, 'UGA', 'Uganda', 'https://flagcdn.com/w320/ug.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (233, 'UKR', 'Ukraine', 'https://flagcdn.com/w320/ua.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (234, 'ARE', 'United Arab Emirates', 'https://flagcdn.com/w320/ae.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (235, 'GBR', 'United Kingdom', 'https://flagcdn.com/w320/gb.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (236, 'USA', 'United States', 'https://flagcdn.com/w320/us.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (237, 'UMI', 'United States Minor Outlying Islands', 'https://flagcdn.com/w320/um.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (238, 'VIR', 'United States Virgin Islands', 'https://flagcdn.com/w320/vi.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (239, 'URY', 'Uruguay', 'https://flagcdn.com/w320/uy.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (240, 'UZB', 'Uzbekistan', 'https://flagcdn.com/w320/uz.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (241, 'VUT', 'Vanuatu', 'https://flagcdn.com/w320/vu.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (242, 'VAT', 'Vatican City', 'https://flagcdn.com/w320/va.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (243, 'VEN', 'Venezuela', 'https://flagcdn.com/w320/ve.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (244, 'VNM', 'Vietnam', 'https://flagcdn.com/w320/vn.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (245, 'WLF', 'Wallis and Futuna', 'https://flagcdn.com/w320/wf.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (246, 'ESH', 'Western Sahara', 'https://flagcdn.com/w320/eh.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (247, 'YEM', 'Yemen', 'https://flagcdn.com/w320/ye.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (248, 'ZMB', 'Zambia', 'https://flagcdn.com/w320/zm.png');
INSERT INTO countries_flags (id, code, name, flag) VALUES (249, 'ZWE', 'Zimbabwe', 'https://flagcdn.com/w320/zw.png');
