// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feeds_service.proto

package feeds

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetFeedListReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedListReq) Reset()         { *m = GetFeedListReq{} }
func (m *GetFeedListReq) String() string { return proto.CompactTextString(m) }
func (*GetFeedListReq) ProtoMessage()    {}
func (*GetFeedListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{0}
}
func (m *GetFeedListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedListReq.Unmarshal(m, b)
}
func (m *GetFeedListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedListReq.Marshal(b, m, deterministic)
}
func (m *GetFeedListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedListReq.Merge(m, src)
}
func (m *GetFeedListReq) XXX_Size() int {
	return xxx_messageInfo_GetFeedListReq.Size(m)
}
func (m *GetFeedListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedListReq proto.InternalMessageInfo

func (m *GetFeedListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserChatDO struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PhotoId              int64    `protobuf:"varint,2,opt,name=photo_id,json=photoId,proto3" json:"photo_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	PeerType             int32    `protobuf:"varint,5,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserChatDO) Reset()         { *m = UserChatDO{} }
func (m *UserChatDO) String() string { return proto.CompactTextString(m) }
func (*UserChatDO) ProtoMessage()    {}
func (*UserChatDO) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{1}
}
func (m *UserChatDO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserChatDO.Unmarshal(m, b)
}
func (m *UserChatDO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserChatDO.Marshal(b, m, deterministic)
}
func (m *UserChatDO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserChatDO.Merge(m, src)
}
func (m *UserChatDO) XXX_Size() int {
	return xxx_messageInfo_UserChatDO.Size(m)
}
func (m *UserChatDO) XXX_DiscardUnknown() {
	xxx_messageInfo_UserChatDO.DiscardUnknown(m)
}

var xxx_messageInfo_UserChatDO proto.InternalMessageInfo

func (m *UserChatDO) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *UserChatDO) GetPhotoId() int64 {
	if m != nil {
		return m.PhotoId
	}
	return 0
}

func (m *UserChatDO) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UserChatDO) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *UserChatDO) GetPeerType() int32 {
	if m != nil {
		return m.PeerType
	}
	return 0
}

type GetFeedListResp struct {
	Data                 []*UserChatDO `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFeedListResp) Reset()         { *m = GetFeedListResp{} }
func (m *GetFeedListResp) String() string { return proto.CompactTextString(m) }
func (*GetFeedListResp) ProtoMessage()    {}
func (*GetFeedListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{2}
}
func (m *GetFeedListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedListResp.Unmarshal(m, b)
}
func (m *GetFeedListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedListResp.Marshal(b, m, deterministic)
}
func (m *GetFeedListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedListResp.Merge(m, src)
}
func (m *GetFeedListResp) XXX_Size() int {
	return xxx_messageInfo_GetFeedListResp.Size(m)
}
func (m *GetFeedListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedListResp proto.InternalMessageInfo

func (m *GetFeedListResp) GetData() []*UserChatDO {
	if m != nil {
		return m.Data
	}
	return nil
}

type FeedInsertItemDO struct {
	ChatId               int64    `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	PeerType             int32    `protobuf:"varint,2,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedInsertItemDO) Reset()         { *m = FeedInsertItemDO{} }
func (m *FeedInsertItemDO) String() string { return proto.CompactTextString(m) }
func (*FeedInsertItemDO) ProtoMessage()    {}
func (*FeedInsertItemDO) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{3}
}
func (m *FeedInsertItemDO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedInsertItemDO.Unmarshal(m, b)
}
func (m *FeedInsertItemDO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedInsertItemDO.Marshal(b, m, deterministic)
}
func (m *FeedInsertItemDO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedInsertItemDO.Merge(m, src)
}
func (m *FeedInsertItemDO) XXX_Size() int {
	return xxx_messageInfo_FeedInsertItemDO.Size(m)
}
func (m *FeedInsertItemDO) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedInsertItemDO.DiscardUnknown(m)
}

var xxx_messageInfo_FeedInsertItemDO proto.InternalMessageInfo

func (m *FeedInsertItemDO) GetChatId() int64 {
	if m != nil {
		return m.ChatId
	}
	return 0
}

func (m *FeedInsertItemDO) GetPeerType() int32 {
	if m != nil {
		return m.PeerType
	}
	return 0
}

type UpdateFeedListReq struct {
	UserId               int64               `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 []*FeedInsertItemDO `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateFeedListReq) Reset()         { *m = UpdateFeedListReq{} }
func (m *UpdateFeedListReq) String() string { return proto.CompactTextString(m) }
func (*UpdateFeedListReq) ProtoMessage()    {}
func (*UpdateFeedListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{4}
}
func (m *UpdateFeedListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeedListReq.Unmarshal(m, b)
}
func (m *UpdateFeedListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeedListReq.Marshal(b, m, deterministic)
}
func (m *UpdateFeedListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeedListReq.Merge(m, src)
}
func (m *UpdateFeedListReq) XXX_Size() int {
	return xxx_messageInfo_UpdateFeedListReq.Size(m)
}
func (m *UpdateFeedListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeedListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeedListReq proto.InternalMessageInfo

func (m *UpdateFeedListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateFeedListReq) GetData() []*FeedInsertItemDO {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateFeedListResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateFeedListResp) Reset()         { *m = UpdateFeedListResp{} }
func (m *UpdateFeedListResp) String() string { return proto.CompactTextString(m) }
func (*UpdateFeedListResp) ProtoMessage()    {}
func (*UpdateFeedListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{5}
}
func (m *UpdateFeedListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateFeedListResp.Unmarshal(m, b)
}
func (m *UpdateFeedListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateFeedListResp.Marshal(b, m, deterministic)
}
func (m *UpdateFeedListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateFeedListResp.Merge(m, src)
}
func (m *UpdateFeedListResp) XXX_Size() int {
	return xxx_messageInfo_UpdateFeedListResp.Size(m)
}
func (m *UpdateFeedListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateFeedListResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateFeedListResp proto.InternalMessageInfo

type GetHistoryCounterReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryCounterReq) Reset()         { *m = GetHistoryCounterReq{} }
func (m *GetHistoryCounterReq) String() string { return proto.CompactTextString(m) }
func (*GetHistoryCounterReq) ProtoMessage()    {}
func (*GetHistoryCounterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{6}
}
func (m *GetHistoryCounterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryCounterReq.Unmarshal(m, b)
}
func (m *GetHistoryCounterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryCounterReq.Marshal(b, m, deterministic)
}
func (m *GetHistoryCounterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryCounterReq.Merge(m, src)
}
func (m *GetHistoryCounterReq) XXX_Size() int {
	return xxx_messageInfo_GetHistoryCounterReq.Size(m)
}
func (m *GetHistoryCounterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryCounterReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryCounterReq proto.InternalMessageInfo

func (m *GetHistoryCounterReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetHistoryCounterResp struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHistoryCounterResp) Reset()         { *m = GetHistoryCounterResp{} }
func (m *GetHistoryCounterResp) String() string { return proto.CompactTextString(m) }
func (*GetHistoryCounterResp) ProtoMessage()    {}
func (*GetHistoryCounterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{7}
}
func (m *GetHistoryCounterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHistoryCounterResp.Unmarshal(m, b)
}
func (m *GetHistoryCounterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHistoryCounterResp.Marshal(b, m, deterministic)
}
func (m *GetHistoryCounterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHistoryCounterResp.Merge(m, src)
}
func (m *GetHistoryCounterResp) XXX_Size() int {
	return xxx_messageInfo_GetHistoryCounterResp.Size(m)
}
func (m *GetHistoryCounterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHistoryCounterResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetHistoryCounterResp proto.InternalMessageInfo

func (m *GetHistoryCounterResp) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetFeedsOffsetListReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Before               int32    `protobuf:"varint,3,opt,name=before,proto3" json:"before,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedsOffsetListReq) Reset()         { *m = GetFeedsOffsetListReq{} }
func (m *GetFeedsOffsetListReq) String() string { return proto.CompactTextString(m) }
func (*GetFeedsOffsetListReq) ProtoMessage()    {}
func (*GetFeedsOffsetListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{8}
}
func (m *GetFeedsOffsetListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedsOffsetListReq.Unmarshal(m, b)
}
func (m *GetFeedsOffsetListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedsOffsetListReq.Marshal(b, m, deterministic)
}
func (m *GetFeedsOffsetListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedsOffsetListReq.Merge(m, src)
}
func (m *GetFeedsOffsetListReq) XXX_Size() int {
	return xxx_messageInfo_GetFeedsOffsetListReq.Size(m)
}
func (m *GetFeedsOffsetListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedsOffsetListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedsOffsetListReq proto.InternalMessageInfo

func (m *GetFeedsOffsetListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetFeedsOffsetListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetFeedsOffsetListReq) GetBefore() int32 {
	if m != nil {
		return m.Before
	}
	return 0
}

type OffsetItemDo struct {
	OffsetMin            int32    `protobuf:"varint,1,opt,name=offset_min,json=offsetMin,proto3" json:"offset_min,omitempty"`
	OffsetMax            int32    `protobuf:"varint,2,opt,name=offset_max,json=offsetMax,proto3" json:"offset_max,omitempty"`
	PeerId               int64    `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Count                int32    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OffsetItemDo) Reset()         { *m = OffsetItemDo{} }
func (m *OffsetItemDo) String() string { return proto.CompactTextString(m) }
func (*OffsetItemDo) ProtoMessage()    {}
func (*OffsetItemDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{9}
}
func (m *OffsetItemDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OffsetItemDo.Unmarshal(m, b)
}
func (m *OffsetItemDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OffsetItemDo.Marshal(b, m, deterministic)
}
func (m *OffsetItemDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OffsetItemDo.Merge(m, src)
}
func (m *OffsetItemDo) XXX_Size() int {
	return xxx_messageInfo_OffsetItemDo.Size(m)
}
func (m *OffsetItemDo) XXX_DiscardUnknown() {
	xxx_messageInfo_OffsetItemDo.DiscardUnknown(m)
}

var xxx_messageInfo_OffsetItemDo proto.InternalMessageInfo

func (m *OffsetItemDo) GetOffsetMin() int32 {
	if m != nil {
		return m.OffsetMin
	}
	return 0
}

func (m *OffsetItemDo) GetOffsetMax() int32 {
	if m != nil {
		return m.OffsetMax
	}
	return 0
}

func (m *OffsetItemDo) GetPeerId() int64 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *OffsetItemDo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetFeedsOffsetListResp struct {
	Data                 []*OffsetItemDo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetFeedsOffsetListResp) Reset()         { *m = GetFeedsOffsetListResp{} }
func (m *GetFeedsOffsetListResp) String() string { return proto.CompactTextString(m) }
func (*GetFeedsOffsetListResp) ProtoMessage()    {}
func (*GetFeedsOffsetListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_31efcc759eeb2667, []int{10}
}
func (m *GetFeedsOffsetListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedsOffsetListResp.Unmarshal(m, b)
}
func (m *GetFeedsOffsetListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedsOffsetListResp.Marshal(b, m, deterministic)
}
func (m *GetFeedsOffsetListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedsOffsetListResp.Merge(m, src)
}
func (m *GetFeedsOffsetListResp) XXX_Size() int {
	return xxx_messageInfo_GetFeedsOffsetListResp.Size(m)
}
func (m *GetFeedsOffsetListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedsOffsetListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedsOffsetListResp proto.InternalMessageInfo

func (m *GetFeedsOffsetListResp) GetData() []*OffsetItemDo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetFeedListReq)(nil), "feeds.GetFeedListReq")
	proto.RegisterType((*UserChatDO)(nil), "feeds.UserChatDO")
	proto.RegisterType((*GetFeedListResp)(nil), "feeds.GetFeedListResp")
	proto.RegisterType((*FeedInsertItemDO)(nil), "feeds.FeedInsertItemDO")
	proto.RegisterType((*UpdateFeedListReq)(nil), "feeds.UpdateFeedListReq")
	proto.RegisterType((*UpdateFeedListResp)(nil), "feeds.UpdateFeedListResp")
	proto.RegisterType((*GetHistoryCounterReq)(nil), "feeds.GetHistoryCounterReq")
	proto.RegisterType((*GetHistoryCounterResp)(nil), "feeds.GetHistoryCounterResp")
	proto.RegisterType((*GetFeedsOffsetListReq)(nil), "feeds.GetFeedsOffsetListReq")
	proto.RegisterType((*OffsetItemDo)(nil), "feeds.OffsetItemDo")
	proto.RegisterType((*GetFeedsOffsetListResp)(nil), "feeds.GetFeedsOffsetListResp")
}

func init() { proto.RegisterFile("feeds_service.proto", fileDescriptor_31efcc759eeb2667) }

var fileDescriptor_31efcc759eeb2667 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0xcd, 0x02, 0x4b, 0xe1, 0xfa, 0xc9, 0x2d, 0x85, 0x2d, 0x6d, 0x13, 0xb2, 0x89, 0x11, 0x63,
	0xc4, 0xa4, 0xbe, 0xf8, 0x2a, 0x18, 0x0b, 0x51, 0x53, 0xb2, 0xb6, 0x31, 0xf6, 0x41, 0xb2, 0x65,
	0x2f, 0xb2, 0x49, 0x61, 0xc7, 0x9d, 0x8b, 0x29, 0xf1, 0x27, 0xf8, 0xcf, 0xfc, 0x55, 0x66, 0x66,
	0xb6, 0xc2, 0x20, 0xc5, 0x3e, 0x9e, 0x7b, 0xee, 0xcc, 0x9c, 0x33, 0xe7, 0xce, 0xc0, 0xee, 0x98,
	0x28, 0x92, 0x43, 0x49, 0xe9, 0x8f, 0x78, 0x44, 0x6d, 0x91, 0x26, 0x9c, 0xa0, 0xab, 0x8b, 0xfe,
	0x33, 0x78, 0x78, 0x42, 0xfc, 0x8e, 0x28, 0xfa, 0x10, 0x4b, 0x0e, 0xe8, 0x3b, 0xd6, 0x61, 0x67,
	0x2e, 0x29, 0x1d, 0xc6, 0x91, 0xe7, 0x34, 0x9d, 0x56, 0x3e, 0x28, 0x2a, 0xd8, 0x8f, 0xfc, 0x5f,
	0x0e, 0xc0, 0xb9, 0xa4, 0xb4, 0x3b, 0x09, 0xf9, 0xed, 0xa9, 0xea, 0x1b, 0x4d, 0x42, 0x5e, 0xe9,
	0x53, 0xb0, 0x1f, 0xe1, 0x3e, 0x94, 0xc4, 0x24, 0xe1, 0x44, 0x31, 0x39, 0xcd, 0xec, 0x68, 0xdc,
	0x8f, 0xb0, 0x0a, 0x2e, 0xc7, 0x7c, 0x45, 0x5e, 0xbe, 0xe9, 0xb4, 0xca, 0x81, 0x01, 0x58, 0x83,
	0xa2, 0xe4, 0x90, 0xe7, 0xd2, 0x2b, 0x34, 0x9d, 0x56, 0x29, 0xc8, 0x10, 0x1e, 0x40, 0x59, 0x10,
	0xa5, 0x43, 0x5e, 0x08, 0xf2, 0xdc, 0xa6, 0xd3, 0x72, 0x83, 0x92, 0x2a, 0x9c, 0x2d, 0x04, 0xf9,
	0xaf, 0xe1, 0x91, 0x25, 0x5c, 0x0a, 0x7c, 0x02, 0x85, 0x28, 0xe4, 0xd0, 0x73, 0x9a, 0xf9, 0xd6,
	0xbd, 0xe3, 0x4a, 0x5b, 0x3b, 0x6c, 0x2f, 0x25, 0x07, 0x9a, 0xf6, 0x7b, 0xf0, 0x58, 0x2d, 0xeb,
	0xcf, 0x24, 0xa5, 0xdc, 0x67, 0x9a, 0x6e, 0x33, 0x63, 0x69, 0xc8, 0xad, 0x69, 0xf8, 0x02, 0x95,
	0x73, 0x11, 0x85, 0x4c, 0x77, 0xb9, 0x3f, 0x7c, 0x9e, 0xc9, 0xcb, 0x69, 0x79, 0xf5, 0x4c, 0xde,
	0xba, 0x94, 0x4c, 0x64, 0x15, 0x70, 0x7d, 0x6b, 0x29, 0xfc, 0x97, 0x50, 0x3d, 0x21, 0xee, 0xc5,
	0x92, 0x93, 0x74, 0xd1, 0x4d, 0xe6, 0x33, 0xa6, 0x74, 0x6b, 0x66, 0x2f, 0x60, 0x6f, 0xc3, 0x02,
	0x29, 0x54, 0x12, 0x23, 0x05, 0x75, 0xbf, 0x1b, 0x18, 0xe0, 0x7f, 0xd5, 0xed, 0xea, 0x48, 0x79,
	0x3a, 0x1e, 0x4b, 0xe2, 0xff, 0x9a, 0xaa, 0x82, 0x7b, 0x15, 0x4f, 0x63, 0xce, 0xee, 0xc6, 0x00,
	0x95, 0xe8, 0x25, 0x8d, 0x93, 0xd4, 0x04, 0xed, 0x06, 0x19, 0xf2, 0x7f, 0xc2, 0x7d, 0xb3, 0xaf,
	0xf6, 0x9a, 0xe0, 0x11, 0x40, 0xa2, 0xf1, 0x70, 0x1a, 0xcf, 0x32, 0x29, 0x65, 0x53, 0xf9, 0x18,
	0xcf, 0x56, 0xe9, 0xf0, 0x3a, 0x3b, 0xe1, 0x86, 0x0e, 0xaf, 0x95, 0x28, 0x9d, 0x4d, 0x1c, 0xe9,
	0x63, 0xf2, 0x41, 0x51, 0x41, 0x23, 0xca, 0x98, 0x2b, 0xac, 0x9a, 0x7b, 0x03, 0xb5, 0x4d, 0xe6,
	0xa4, 0xc0, 0xa7, 0xd6, 0xe0, 0xec, 0x66, 0xc9, 0xac, 0x2a, 0x35, 0xa9, 0x1c, 0xff, 0xce, 0x41,
	0x29, 0x18, 0x74, 0xf5, 0x1e, 0xd8, 0x81, 0x8a, 0x79, 0x58, 0xdf, 0x96, 0x73, 0x88, 0x7b, 0xd9,
	0x62, 0xfb, 0x51, 0x35, 0x6a, 0x9b, 0xca, 0x52, 0xe0, 0x7b, 0xa8, 0x9a, 0x3d, 0xe6, 0x56, 0xd8,
	0xe8, 0xdd, 0x0c, 0xef, 0xfa, 0x78, 0x35, 0xf6, 0x6f, 0x61, 0xa4, 0xc0, 0x33, 0xa8, 0xff, 0x15,
	0x64, 0x47, 0x8e, 0x07, 0xcb, 0xf3, 0xff, 0x99, 0x9e, 0xc6, 0xe1, 0xed, 0xa4, 0x14, 0xf8, 0x19,
	0x3c, 0xcb, 0xe6, 0xca, 0xe5, 0xe1, 0xa1, 0x6d, 0xcb, 0x1e, 0x9a, 0xc6, 0xd1, 0x16, 0x56, 0x8a,
	0x4e, 0x1b, 0x1e, 0x58, 0x1f, 0x53, 0x07, 0x2f, 0x06, 0xea, 0x6b, 0xd2, 0xbd, 0x9f, 0x4c, 0xad,
	0x97, 0x1b, 0x38, 0x17, 0xe6, 0xab, 0xba, 0x2c, 0xea, 0x8f, 0xeb, 0xd5, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0xa9, 0xe0, 0x58, 0xcf, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCFeedsClient is the client API for RPCFeeds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCFeedsClient interface {
	FeedsGetFeedList(ctx context.Context, in *GetFeedListReq, opts ...grpc.CallOption) (*GetFeedListResp, error)
	FeedsUpdateFeedList(ctx context.Context, in *UpdateFeedListReq, opts ...grpc.CallOption) (*UpdateFeedListResp, error)
	FeedsGetHistoryCounter(ctx context.Context, in *GetHistoryCounterReq, opts ...grpc.CallOption) (*GetHistoryCounterResp, error)
	FeedsGetFeedsOffsetList(ctx context.Context, in *GetFeedsOffsetListReq, opts ...grpc.CallOption) (*GetFeedsOffsetListResp, error)
}

type rPCFeedsClient struct {
	cc *grpc.ClientConn
}

func NewRPCFeedsClient(cc *grpc.ClientConn) RPCFeedsClient {
	return &rPCFeedsClient{cc}
}

func (c *rPCFeedsClient) FeedsGetFeedList(ctx context.Context, in *GetFeedListReq, opts ...grpc.CallOption) (*GetFeedListResp, error) {
	out := new(GetFeedListResp)
	err := c.cc.Invoke(ctx, "/feeds.RPCFeeds/feeds_getFeedList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCFeedsClient) FeedsUpdateFeedList(ctx context.Context, in *UpdateFeedListReq, opts ...grpc.CallOption) (*UpdateFeedListResp, error) {
	out := new(UpdateFeedListResp)
	err := c.cc.Invoke(ctx, "/feeds.RPCFeeds/feeds_updateFeedList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCFeedsClient) FeedsGetHistoryCounter(ctx context.Context, in *GetHistoryCounterReq, opts ...grpc.CallOption) (*GetHistoryCounterResp, error) {
	out := new(GetHistoryCounterResp)
	err := c.cc.Invoke(ctx, "/feeds.RPCFeeds/feeds_getHistoryCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCFeedsClient) FeedsGetFeedsOffsetList(ctx context.Context, in *GetFeedsOffsetListReq, opts ...grpc.CallOption) (*GetFeedsOffsetListResp, error) {
	out := new(GetFeedsOffsetListResp)
	err := c.cc.Invoke(ctx, "/feeds.RPCFeeds/feeds_getFeedsOffsetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCFeedsServer is the server API for RPCFeeds service.
type RPCFeedsServer interface {
	FeedsGetFeedList(context.Context, *GetFeedListReq) (*GetFeedListResp, error)
	FeedsUpdateFeedList(context.Context, *UpdateFeedListReq) (*UpdateFeedListResp, error)
	FeedsGetHistoryCounter(context.Context, *GetHistoryCounterReq) (*GetHistoryCounterResp, error)
	FeedsGetFeedsOffsetList(context.Context, *GetFeedsOffsetListReq) (*GetFeedsOffsetListResp, error)
}

// UnimplementedRPCFeedsServer can be embedded to have forward compatible implementations.
type UnimplementedRPCFeedsServer struct {
}

func (*UnimplementedRPCFeedsServer) FeedsGetFeedList(ctx context.Context, req *GetFeedListReq) (*GetFeedListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedsGetFeedList not implemented")
}
func (*UnimplementedRPCFeedsServer) FeedsUpdateFeedList(ctx context.Context, req *UpdateFeedListReq) (*UpdateFeedListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedsUpdateFeedList not implemented")
}
func (*UnimplementedRPCFeedsServer) FeedsGetHistoryCounter(ctx context.Context, req *GetHistoryCounterReq) (*GetHistoryCounterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedsGetHistoryCounter not implemented")
}
func (*UnimplementedRPCFeedsServer) FeedsGetFeedsOffsetList(ctx context.Context, req *GetFeedsOffsetListReq) (*GetFeedsOffsetListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeedsGetFeedsOffsetList not implemented")
}

func RegisterRPCFeedsServer(s *grpc.Server, srv RPCFeedsServer) {
	s.RegisterService(&_RPCFeeds_serviceDesc, srv)
}

func _RPCFeeds_FeedsGetFeedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFeedsServer).FeedsGetFeedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeds.RPCFeeds/FeedsGetFeedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFeedsServer).FeedsGetFeedList(ctx, req.(*GetFeedListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCFeeds_FeedsUpdateFeedList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFeedsServer).FeedsUpdateFeedList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeds.RPCFeeds/FeedsUpdateFeedList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFeedsServer).FeedsUpdateFeedList(ctx, req.(*UpdateFeedListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCFeeds_FeedsGetHistoryCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryCounterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFeedsServer).FeedsGetHistoryCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeds.RPCFeeds/FeedsGetHistoryCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFeedsServer).FeedsGetHistoryCounter(ctx, req.(*GetHistoryCounterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCFeeds_FeedsGetFeedsOffsetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedsOffsetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCFeedsServer).FeedsGetFeedsOffsetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feeds.RPCFeeds/FeedsGetFeedsOffsetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCFeedsServer).FeedsGetFeedsOffsetList(ctx, req.(*GetFeedsOffsetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCFeeds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feeds.RPCFeeds",
	HandlerType: (*RPCFeedsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "feeds_getFeedList",
			Handler:    _RPCFeeds_FeedsGetFeedList_Handler,
		},
		{
			MethodName: "feeds_updateFeedList",
			Handler:    _RPCFeeds_FeedsUpdateFeedList_Handler,
		},
		{
			MethodName: "feeds_getHistoryCounter",
			Handler:    _RPCFeeds_FeedsGetHistoryCounter_Handler,
		},
		{
			MethodName: "feeds_getFeedsOffsetList",
			Handler:    _RPCFeeds_FeedsGetFeedsOffsetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeds_service.proto",
}
