// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authorization_service.proto

package authorization

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MData struct {
	ServerId             string   `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ClientAddr           string   `protobuf:"bytes,2,opt,name=client_addr,json=clientAddr,proto3" json:"client_addr,omitempty"`
	AuthId               int64    `protobuf:"varint,3,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	SessionId            int64    `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReceiveTime          int64    `protobuf:"varint,5,opt,name=receive_time,json=receiveTime,proto3" json:"receive_time,omitempty"`
	UserId               int64    `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientMsgId          int64    `protobuf:"varint,7,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	IsBot                bool     `protobuf:"varint,8,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	Layer                int32    `protobuf:"varint,9,opt,name=layer,proto3" json:"layer,omitempty"`
	Client               string   `protobuf:"bytes,10,opt,name=client,proto3" json:"client,omitempty"`
	IsAdmin              bool     `protobuf:"varint,11,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Langpack             string   `protobuf:"bytes,13,opt,name=langpack,proto3" json:"langpack,omitempty"`
	PermAuthKeyId        int64    `protobuf:"varint,14,opt,name=perm_auth_key_id,json=permAuthKeyId,proto3" json:"perm_auth_key_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MData) Reset()         { *m = MData{} }
func (m *MData) String() string { return proto.CompactTextString(m) }
func (*MData) ProtoMessage()    {}
func (*MData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{0}
}
func (m *MData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MData.Unmarshal(m, b)
}
func (m *MData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MData.Marshal(b, m, deterministic)
}
func (m *MData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MData.Merge(m, src)
}
func (m *MData) XXX_Size() int {
	return xxx_messageInfo_MData.Size(m)
}
func (m *MData) XXX_DiscardUnknown() {
	xxx_messageInfo_MData.DiscardUnknown(m)
}

var xxx_messageInfo_MData proto.InternalMessageInfo

func (m *MData) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *MData) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

func (m *MData) GetAuthId() int64 {
	if m != nil {
		return m.AuthId
	}
	return 0
}

func (m *MData) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *MData) GetReceiveTime() int64 {
	if m != nil {
		return m.ReceiveTime
	}
	return 0
}

func (m *MData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MData) GetClientMsgId() int64 {
	if m != nil {
		return m.ClientMsgId
	}
	return 0
}

func (m *MData) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func (m *MData) GetLayer() int32 {
	if m != nil {
		return m.Layer
	}
	return 0
}

func (m *MData) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *MData) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *MData) GetLangpack() string {
	if m != nil {
		return m.Langpack
	}
	return ""
}

func (m *MData) GetPermAuthKeyId() int64 {
	if m != nil {
		return m.PermAuthKeyId
	}
	return 0
}

type AuthSignUpRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth          string   `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode          string   `protobuf:"bytes,7,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Avatar               string   `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FirstName            string   `protobuf:"bytes,9,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,10,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MData                *MData   `protobuf:"bytes,11,opt,name=m_data,json=mData,proto3" json:"m_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSignUpRequest) Reset()         { *m = AuthSignUpRequest{} }
func (m *AuthSignUpRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSignUpRequest) ProtoMessage()    {}
func (*AuthSignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{1}
}
func (m *AuthSignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignUpRequest.Unmarshal(m, b)
}
func (m *AuthSignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignUpRequest.Marshal(b, m, deterministic)
}
func (m *AuthSignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignUpRequest.Merge(m, src)
}
func (m *AuthSignUpRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSignUpRequest.Size(m)
}
func (m *AuthSignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignUpRequest proto.InternalMessageInfo

func (m *AuthSignUpRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthSignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthSignUpRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *AuthSignUpRequest) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *AuthSignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthSignUpRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AuthSignUpRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *AuthSignUpRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AuthSignUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AuthSignUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AuthSignUpRequest) GetMData() *MData {
	if m != nil {
		return m.MData
	}
	return nil
}

type AuthSignInRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSignInRequest) Reset()         { *m = AuthSignInRequest{} }
func (m *AuthSignInRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSignInRequest) ProtoMessage()    {}
func (*AuthSignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{2}
}
func (m *AuthSignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignInRequest.Unmarshal(m, b)
}
func (m *AuthSignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignInRequest.Marshal(b, m, deterministic)
}
func (m *AuthSignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignInRequest.Merge(m, src)
}
func (m *AuthSignInRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSignInRequest.Size(m)
}
func (m *AuthSignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignInRequest proto.InternalMessageInfo

func (m *AuthSignInRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthSignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthSignUpRsp struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationExpire   int64    `protobuf:"varint,2,opt,name=confirmation_expire,json=confirmationExpire,proto3" json:"confirmation_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSignUpRsp) Reset()         { *m = AuthSignUpRsp{} }
func (m *AuthSignUpRsp) String() string { return proto.CompactTextString(m) }
func (*AuthSignUpRsp) ProtoMessage()    {}
func (*AuthSignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{3}
}
func (m *AuthSignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSignUpRsp.Unmarshal(m, b)
}
func (m *AuthSignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSignUpRsp.Marshal(b, m, deterministic)
}
func (m *AuthSignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSignUpRsp.Merge(m, src)
}
func (m *AuthSignUpRsp) XXX_Size() int {
	return xxx_messageInfo_AuthSignUpRsp.Size(m)
}
func (m *AuthSignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSignUpRsp proto.InternalMessageInfo

func (m *AuthSignUpRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthSignUpRsp) GetConfirmationExpire() int64 {
	if m != nil {
		return m.ConfirmationExpire
	}
	return 0
}

type ConfirmationRequest struct {
	UsernameOrEmail      string   `protobuf:"bytes,1,opt,name=username_or_email,json=usernameOrEmail,proto3" json:"username_or_email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationRequest) Reset()         { *m = ConfirmationRequest{} }
func (m *ConfirmationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmationRequest) ProtoMessage()    {}
func (*ConfirmationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{4}
}
func (m *ConfirmationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationRequest.Unmarshal(m, b)
}
func (m *ConfirmationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationRequest.Merge(m, src)
}
func (m *ConfirmationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmationRequest.Size(m)
}
func (m *ConfirmationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationRequest proto.InternalMessageInfo

func (m *ConfirmationRequest) GetUsernameOrEmail() string {
	if m != nil {
		return m.UsernameOrEmail
	}
	return ""
}

func (m *ConfirmationRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ConfirmationResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationResponse) Reset()         { *m = ConfirmationResponse{} }
func (m *ConfirmationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmationResponse) ProtoMessage()    {}
func (*ConfirmationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{5}
}
func (m *ConfirmationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationResponse.Unmarshal(m, b)
}
func (m *ConfirmationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationResponse.Merge(m, src)
}
func (m *ConfirmationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmationResponse.Size(m)
}
func (m *ConfirmationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationResponse proto.InternalMessageInfo

func (m *ConfirmationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MData)(nil), "authorization.MData")
	proto.RegisterType((*AuthSignUpRequest)(nil), "authorization.AuthSignUpRequest")
	proto.RegisterType((*AuthSignInRequest)(nil), "authorization.AuthSignInRequest")
	proto.RegisterType((*AuthSignUpRsp)(nil), "authorization.AuthSignUpRsp")
	proto.RegisterType((*ConfirmationRequest)(nil), "authorization.ConfirmationRequest")
	proto.RegisterType((*ConfirmationResponse)(nil), "authorization.ConfirmationResponse")
}

func init() { proto.RegisterFile("authorization_service.proto", fileDescriptor_e27dc8f5aa0b42d7) }

var fileDescriptor_e27dc8f5aa0b42d7 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x73, 0x1a, 0x37,
	0x14, 0x1d, 0xc0, 0x7c, 0xec, 0xc5, 0xb4, 0xb6, 0xfc, 0xd1, 0x2d, 0xb4, 0x53, 0xba, 0x7d, 0x28,
	0xd3, 0xce, 0xe0, 0x8e, 0xfb, 0x0b, 0xc0, 0xb5, 0xa7, 0xd4, 0x75, 0xec, 0x59, 0xc7, 0xc9, 0x8c,
	0x5f, 0x76, 0x04, 0xba, 0x2c, 0x1a, 0xb3, 0xab, 0x8d, 0x24, 0x9c, 0x90, 0xb7, 0xbc, 0xe5, 0x1f,
	0xe6, 0xef, 0x64, 0x24, 0xed, 0x1a, 0x70, 0xec, 0xbc, 0xe4, 0x09, 0xce, 0x39, 0xd2, 0xd5, 0xbd,
	0xe7, 0x68, 0x05, 0x1d, 0xba, 0xd0, 0x33, 0x21, 0xf9, 0x7b, 0xaa, 0xb9, 0x48, 0x23, 0x85, 0xf2,
	0x9e, 0x4f, 0xb0, 0x9f, 0x49, 0xa1, 0x05, 0x69, 0x6d, 0x88, 0xed, 0x4e, 0x2c, 0x44, 0x3c, 0xc7,
	0x23, 0x2b, 0x8e, 0x17, 0xd3, 0x23, 0x4c, 0x32, 0xbd, 0x74, 0x6b, 0x83, 0x8f, 0x15, 0xa8, 0x5e,
	0xfc, 0x43, 0x35, 0x25, 0x1d, 0xf0, 0x4c, 0x19, 0x94, 0x11, 0x67, 0x7e, 0xa9, 0x5b, 0xea, 0x79,
	0x61, 0xc3, 0x11, 0x23, 0x46, 0x7e, 0x81, 0xe6, 0x64, 0xce, 0x31, 0xd5, 0x11, 0x65, 0x4c, 0xfa,
	0x65, 0x2b, 0x83, 0xa3, 0x06, 0x8c, 0x49, 0xf2, 0x03, 0xd4, 0xcd, 0xa9, 0x66, 0x6f, 0xa5, 0x5b,
	0xea, 0x55, 0xc2, 0x9a, 0x81, 0x23, 0x46, 0x7e, 0x06, 0x50, 0xa8, 0x94, 0xe9, 0x92, 0x33, 0x7f,
	0xcb, 0x6a, 0x5e, 0xce, 0x8c, 0x18, 0xf9, 0x15, 0xb6, 0x25, 0x4e, 0x90, 0xdf, 0x63, 0xa4, 0x79,
	0x82, 0x7e, 0xd5, 0x2e, 0x68, 0xe6, 0xdc, 0x4b, 0x9e, 0xa0, 0x29, 0xbd, 0x50, 0xae, 0xad, 0x9a,
	0x2b, 0x6d, 0xe0, 0x88, 0x91, 0x00, 0x5a, 0x79, 0x53, 0x89, 0x8a, 0x8d, 0x5c, 0x77, 0x9b, 0x1d,
	0x79, 0xa1, 0xe2, 0x11, 0x23, 0x07, 0x50, 0xe3, 0x2a, 0x1a, 0x0b, 0xed, 0x37, 0xba, 0xa5, 0x5e,
	0x23, 0xac, 0x72, 0x35, 0x14, 0x9a, 0xec, 0x43, 0x75, 0x4e, 0x97, 0x28, 0x7d, 0xaf, 0x5b, 0xea,
	0x55, 0x43, 0x07, 0xc8, 0x21, 0xd4, 0xdc, 0x5e, 0x1f, 0xec, 0x80, 0x39, 0x22, 0x3f, 0x42, 0x83,
	0xab, 0x88, 0xb2, 0x84, 0xa7, 0x7e, 0xd3, 0x96, 0xa9, 0x73, 0x35, 0x30, 0x90, 0xb4, 0xa1, 0x31,
	0xa7, 0x69, 0x9c, 0xd1, 0xc9, 0x9d, 0xdf, 0x72, 0xa6, 0x15, 0x98, 0xfc, 0x0e, 0x3b, 0x19, 0xca,
	0x24, 0xb2, 0xc6, 0xdc, 0xe1, 0xd2, 0xb4, 0xf8, 0x9d, 0x6d, 0xb1, 0x65, 0xf8, 0xc1, 0x42, 0xcf,
	0xce, 0x71, 0x39, 0x62, 0xff, 0x6d, 0x35, 0xb6, 0x77, 0x5a, 0xc1, 0xa7, 0x32, 0xec, 0x1a, 0xee,
	0x9a, 0xc7, 0xe9, 0x4d, 0x16, 0xe2, 0x9b, 0x05, 0x2a, 0x6d, 0x0e, 0x30, 0xe3, 0xa6, 0x34, 0xc1,
	0x22, 0x95, 0x02, 0x1b, 0x2d, 0xa3, 0x4a, 0xbd, 0x15, 0x92, 0xe5, 0x91, 0x3c, 0x60, 0x33, 0x4b,
	0x8c, 0x29, 0x43, 0x69, 0xf3, 0xf0, 0xc2, 0x1c, 0x19, 0xd3, 0x18, 0xd5, 0x18, 0x89, 0x69, 0x34,
	0xe6, 0x52, 0xcf, 0x6c, 0x24, 0x5e, 0xd8, 0x34, 0xe4, 0xe5, 0x74, 0x68, 0x28, 0xe3, 0x0e, 0x26,
	0x94, 0xcf, 0x6d, 0x1a, 0x5e, 0xe8, 0x80, 0x61, 0xb3, 0x99, 0x48, 0xd1, 0xa6, 0xe0, 0x85, 0x0e,
	0x98, 0x00, 0x27, 0x62, 0x91, 0x6a, 0xb9, 0x8c, 0x26, 0x82, 0xa1, 0xcd, 0xc0, 0x0b, 0x9b, 0x39,
	0x77, 0x22, 0x18, 0x9a, 0x56, 0xe8, 0x3d, 0xd5, 0x54, 0xda, 0x0c, 0xbc, 0x30, 0x47, 0xe6, 0x6a,
	0x4c, 0xb9, 0x54, 0x3a, 0xb2, 0xc3, 0x79, 0x56, 0xf3, 0x2c, 0xf3, 0xc2, 0x4c, 0xd7, 0x01, 0x6f,
	0x4e, 0x0b, 0x15, 0x0a, 0x6f, 0x73, 0xf1, 0x4f, 0xa8, 0x25, 0x11, 0xa3, 0x9a, 0xda, 0x40, 0x9a,
	0xc7, 0xfb, 0xfd, 0x8d, 0x4b, 0xdf, 0xb7, 0x77, 0x3a, 0xac, 0x26, 0xe6, 0x27, 0x38, 0x5f, 0x19,
	0x3b, 0x4a, 0xbf, 0xd1, 0xd8, 0xe0, 0x15, 0xb4, 0xd6, 0x52, 0x52, 0xd9, 0xca, 0xad, 0xd2, 0xba,
	0x5b, 0x47, 0xb0, 0x37, 0x11, 0xe9, 0x94, 0xcb, 0xc4, 0x7d, 0xa2, 0xf8, 0x2e, 0xe3, 0x12, 0x6d,
	0xb5, 0x4a, 0x48, 0xd6, 0xa5, 0x53, 0xab, 0x04, 0x37, 0xb0, 0x77, 0xb2, 0xc6, 0x16, 0x6d, 0xfe,
	0x01, 0xbb, 0x45, 0x5b, 0x91, 0x90, 0xd1, 0xfa, 0x49, 0xdf, 0x17, 0xc2, 0xa5, 0x3c, 0xb5, 0x67,
	0x12, 0xd8, 0xb2, 0x19, 0xb8, 0x96, 0xed, 0xff, 0xe0, 0x2f, 0xd8, 0xdf, 0x2c, 0xab, 0x32, 0x91,
	0x2a, 0x24, 0x3e, 0xd4, 0x13, 0x54, 0x8a, 0xc6, 0xc5, 0xf4, 0x05, 0x3c, 0xfe, 0x50, 0x86, 0x9d,
	0xf0, 0xea, 0x64, 0xb0, 0xee, 0x27, 0x39, 0x03, 0x58, 0x59, 0x48, 0xba, 0x8f, 0xdc, 0xfe, 0xc2,
	0xdd, 0xf6, 0x61, 0xdf, 0xbd, 0x3a, 0xfd, 0xe2, 0xd5, 0xe9, 0x9f, 0x9a, 0x57, 0x87, 0xfc, 0xbf,
	0xaa, 0x73, 0x93, 0x3d, 0x5b, 0xe7, 0xe1, 0xfa, 0xb7, 0x7f, 0x7a, 0x7e, 0x85, 0xca, 0xc8, 0x6b,
	0xd8, 0x5e, 0x1f, 0x8e, 0x04, 0x8f, 0x56, 0x3f, 0x61, 0x68, 0xfb, 0xb7, 0xaf, 0xae, 0x71, 0xee,
	0x0c, 0xcf, 0xe0, 0xe0, 0xc9, 0x17, 0x76, 0xd8, 0xbe, 0xbd, 0x32, 0x03, 0x6d, 0x98, 0x73, 0xed,
	0xb4, 0x7f, 0xcb, 0x57, 0xa5, 0xdb, 0xcd, 0xb7, 0x77, 0x5c, 0xb3, 0xe3, 0xff, 0xfd, 0x39, 0x00,
	0x00, 0xff, 0xff, 0x82, 0x79, 0xfa, 0xf9, 0xb0, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCAuthorizationClient is the client API for RPCAuthorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCAuthorizationClient interface {
	AuthSignIn(ctx context.Context, in *AuthSignInRequest, opts ...grpc.CallOption) (*types.Empty, error)
	AuthSignUp(ctx context.Context, in *AuthSignUpRequest, opts ...grpc.CallOption) (*AuthSignUpRsp, error)
	Confirmation(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error)
}

type rPCAuthorizationClient struct {
	cc *grpc.ClientConn
}

func NewRPCAuthorizationClient(cc *grpc.ClientConn) RPCAuthorizationClient {
	return &rPCAuthorizationClient{cc}
}

func (c *rPCAuthorizationClient) AuthSignIn(ctx context.Context, in *AuthSignInRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/authorization.RPCAuthorization/AuthSignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAuthorizationClient) AuthSignUp(ctx context.Context, in *AuthSignUpRequest, opts ...grpc.CallOption) (*AuthSignUpRsp, error) {
	out := new(AuthSignUpRsp)
	err := c.cc.Invoke(ctx, "/authorization.RPCAuthorization/AuthSignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAuthorizationClient) Confirmation(ctx context.Context, in *ConfirmationRequest, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, "/authorization.RPCAuthorization/Confirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCAuthorizationServer is the server API for RPCAuthorization service.
type RPCAuthorizationServer interface {
	AuthSignIn(context.Context, *AuthSignInRequest) (*types.Empty, error)
	AuthSignUp(context.Context, *AuthSignUpRequest) (*AuthSignUpRsp, error)
	Confirmation(context.Context, *ConfirmationRequest) (*ConfirmationResponse, error)
}

// UnimplementedRPCAuthorizationServer can be embedded to have forward compatible implementations.
type UnimplementedRPCAuthorizationServer struct {
}

func (*UnimplementedRPCAuthorizationServer) AuthSignIn(ctx context.Context, req *AuthSignInRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSignIn not implemented")
}
func (*UnimplementedRPCAuthorizationServer) AuthSignUp(ctx context.Context, req *AuthSignUpRequest) (*AuthSignUpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSignUp not implemented")
}
func (*UnimplementedRPCAuthorizationServer) Confirmation(ctx context.Context, req *ConfirmationRequest) (*ConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Confirmation not implemented")
}

func RegisterRPCAuthorizationServer(s *grpc.Server, srv RPCAuthorizationServer) {
	s.RegisterService(&_RPCAuthorization_serviceDesc, srv)
}

func _RPCAuthorization_AuthSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).AuthSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.RPCAuthorization/AuthSignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).AuthSignIn(ctx, req.(*AuthSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAuthorization_AuthSignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).AuthSignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.RPCAuthorization/AuthSignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).AuthSignUp(ctx, req.(*AuthSignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAuthorization_Confirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).Confirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.RPCAuthorization/Confirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).Confirmation(ctx, req.(*ConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCAuthorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authorization.RPCAuthorization",
	HandlerType: (*RPCAuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthSignIn",
			Handler:    _RPCAuthorization_AuthSignIn_Handler,
		},
		{
			MethodName: "AuthSignUp",
			Handler:    _RPCAuthorization_AuthSignUp_Handler,
		},
		{
			MethodName: "Confirmation",
			Handler:    _RPCAuthorization_Confirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorization_service.proto",
}
