// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authorization_service.proto

package authorization

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthSingUpRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth          string   `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	CountryCode          string   `protobuf:"bytes,7,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Avatar               string   `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FirstName            string   `protobuf:"bytes,9,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,10,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingUpRequest) Reset()         { *m = AuthSingUpRequest{} }
func (m *AuthSingUpRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSingUpRequest) ProtoMessage()    {}
func (*AuthSingUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{0}
}
func (m *AuthSingUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingUpRequest.Unmarshal(m, b)
}
func (m *AuthSingUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingUpRequest.Marshal(b, m, deterministic)
}
func (m *AuthSingUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingUpRequest.Merge(m, src)
}
func (m *AuthSingUpRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSingUpRequest.Size(m)
}
func (m *AuthSingUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingUpRequest proto.InternalMessageInfo

func (m *AuthSingUpRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthSingUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthSingUpRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *AuthSingUpRequest) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *AuthSingUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthSingUpRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AuthSingUpRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *AuthSingUpRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AuthSingUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AuthSingUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type AuthSingInRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingInRequest) Reset()         { *m = AuthSingInRequest{} }
func (m *AuthSingInRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSingInRequest) ProtoMessage()    {}
func (*AuthSingInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{1}
}
func (m *AuthSingInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingInRequest.Unmarshal(m, b)
}
func (m *AuthSingInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingInRequest.Marshal(b, m, deterministic)
}
func (m *AuthSingInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingInRequest.Merge(m, src)
}
func (m *AuthSingInRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSingInRequest.Size(m)
}
func (m *AuthSingInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingInRequest proto.InternalMessageInfo

func (m *AuthSingInRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthSingInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthSingUpRsp struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationExpire   int64    `protobuf:"varint,2,opt,name=confirmation_expire,json=confirmationExpire,proto3" json:"confirmation_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingUpRsp) Reset()         { *m = AuthSingUpRsp{} }
func (m *AuthSingUpRsp) String() string { return proto.CompactTextString(m) }
func (*AuthSingUpRsp) ProtoMessage()    {}
func (*AuthSingUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{2}
}
func (m *AuthSingUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingUpRsp.Unmarshal(m, b)
}
func (m *AuthSingUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingUpRsp.Marshal(b, m, deterministic)
}
func (m *AuthSingUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingUpRsp.Merge(m, src)
}
func (m *AuthSingUpRsp) XXX_Size() int {
	return xxx_messageInfo_AuthSingUpRsp.Size(m)
}
func (m *AuthSingUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingUpRsp proto.InternalMessageInfo

func (m *AuthSingUpRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthSingUpRsp) GetConfirmationExpire() int64 {
	if m != nil {
		return m.ConfirmationExpire
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthSingUpRequest)(nil), "authorization.AuthSingUpRequest")
	proto.RegisterType((*AuthSingInRequest)(nil), "authorization.AuthSingInRequest")
	proto.RegisterType((*AuthSingUpRsp)(nil), "authorization.AuthSingUpRsp")
}

func init() { proto.RegisterFile("authorization_service.proto", fileDescriptor_e27dc8f5aa0b42d7) }

var fileDescriptor_e27dc8f5aa0b42d7 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x51, 0x6f, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0x8e, 0x95, 0xe5, 0x42, 0x25, 0x30, 0x30, 0x59, 0x29, 0x48, 0x23, 0x4f, 0x3c,
	0xa5, 0x12, 0xfc, 0x82, 0x75, 0xda, 0xc4, 0x04, 0x82, 0x2a, 0xd3, 0x78, 0xd8, 0x4b, 0xe4, 0x26,
	0x37, 0x89, 0xa5, 0xc6, 0x36, 0xb6, 0x33, 0x18, 0xbf, 0x08, 0xf1, 0x2b, 0x91, 0xed, 0x75, 0x4d,
	0x04, 0x7b, 0xda, 0xe3, 0x39, 0x5f, 0x74, 0x7d, 0xef, 0xc9, 0x81, 0x39, 0xeb, 0x6d, 0x2b, 0x35,
	0xff, 0xc5, 0x2c, 0x97, 0xa2, 0x30, 0xa8, 0xaf, 0x79, 0x89, 0x99, 0xd2, 0xd2, 0x4a, 0x32, 0x1b,
	0xc1, 0x64, 0xde, 0x48, 0xd9, 0x6c, 0x70, 0xe1, 0xe1, 0xba, 0xaf, 0x17, 0xd8, 0x29, 0x7b, 0x13,
	0xbe, 0x4d, 0xff, 0x4c, 0xe0, 0xf9, 0x71, 0x6f, 0xdb, 0x0b, 0x2e, 0x9a, 0x4b, 0x95, 0xe3, 0xf7,
	0x1e, 0x8d, 0x25, 0x09, 0x1c, 0xf4, 0x06, 0xb5, 0x60, 0x1d, 0xd2, 0xe8, 0x28, 0x7a, 0x17, 0xe7,
	0x77, 0xda, 0x31, 0xc5, 0x8c, 0xf9, 0x21, 0x75, 0x45, 0x27, 0x81, 0x6d, 0x35, 0x39, 0x84, 0x69,
	0x83, 0xa2, 0x42, 0x4d, 0xf7, 0x3c, 0xb9, 0x55, 0x24, 0x85, 0x59, 0xc5, 0x2c, 0x16, 0xb2, 0x2e,
	0xd6, 0x5c, 0xdb, 0x96, 0x3e, 0xf2, 0xf8, 0x89, 0x33, 0xbf, 0xd6, 0x4b, 0x67, 0x91, 0x97, 0xb0,
	0x8f, 0x1d, 0xe3, 0x1b, 0xba, 0xef, 0x59, 0x10, 0xce, 0x55, 0xad, 0x14, 0x48, 0xa7, 0xc1, 0xf5,
	0x82, 0xbc, 0x85, 0xa7, 0xa5, 0xec, 0x85, 0xd5, 0x37, 0x45, 0x29, 0x2b, 0xa4, 0x8f, 0xc3, 0xb8,
	0x5b, 0xef, 0x44, 0x56, 0xe8, 0x56, 0x61, 0xd7, 0xcc, 0x32, 0x4d, 0x0f, 0xc2, 0x2a, 0x41, 0x91,
	0x37, 0x00, 0x35, 0xd7, 0xc6, 0x16, 0xfe, 0xb8, 0xd8, 0xb3, 0xd8, 0x3b, 0x5f, 0xdc, 0x75, 0x73,
	0x88, 0x37, 0x6c, 0x4b, 0x21, 0x9c, 0xe7, 0x0c, 0x07, 0xd3, 0x4f, 0xbb, 0xac, 0xce, 0xc5, 0x03,
	0xb3, 0x4a, 0xbf, 0xc1, 0x6c, 0x10, 0xbc, 0x51, 0xbb, 0x00, 0xa2, 0x61, 0x00, 0x0b, 0x78, 0x51,
	0x4a, 0x51, 0x73, 0xdd, 0x85, 0x5f, 0x8d, 0x3f, 0x15, 0xd7, 0xe8, 0xa7, 0xed, 0xe5, 0x64, 0x88,
	0x4e, 0x3d, 0x79, 0xff, 0x3b, 0x82, 0x67, 0xf9, 0xea, 0xe4, 0x78, 0xd8, 0x01, 0x72, 0x06, 0x10,
	0x1e, 0x6b, 0xc4, 0xb9, 0x20, 0x47, 0xd9, 0xa8, 0x21, 0xd9, 0x3f, 0x47, 0x25, 0x87, 0x59, 0x28,
	0x4d, 0xb6, 0x2d, 0x4d, 0x76, 0xea, 0x4a, 0x43, 0x3e, 0xef, 0xe6, 0x5c, 0xaa, 0x7b, 0xe7, 0xdc,
	0x15, 0x29, 0x79, 0x7d, 0xff, 0x17, 0x46, 0x2d, 0xcf, 0xe0, 0xd5, 0x7f, 0x7b, 0xbc, 0x4c, 0xae,
	0x56, 0xee, 0xdd, 0xd1, 0x0d, 0x17, 0x81, 0x7d, 0x9c, 0xac, 0xa2, 0xab, 0x71, 0xc3, 0xd7, 0x53,
	0xbf, 0xe5, 0x87, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x98, 0xb3, 0xe0, 0xc8, 0x16, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCAuthorizationClient is the client API for RPCAuthorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCAuthorizationClient interface {
	AuthSignIn(ctx context.Context, in *AuthSingInRequest, opts ...grpc.CallOption) (*types.Empty, error)
	AuthSignUp(ctx context.Context, in *AuthSingUpRequest, opts ...grpc.CallOption) (*AuthSingUpRsp, error)
}

type rPCAuthorizationClient struct {
	cc *grpc.ClientConn
}

func NewRPCAuthorizationClient(cc *grpc.ClientConn) RPCAuthorizationClient {
	return &rPCAuthorizationClient{cc}
}

func (c *rPCAuthorizationClient) AuthSignIn(ctx context.Context, in *AuthSingInRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/authorization.RPCAuthorization/AuthSignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAuthorizationClient) AuthSignUp(ctx context.Context, in *AuthSingUpRequest, opts ...grpc.CallOption) (*AuthSingUpRsp, error) {
	out := new(AuthSingUpRsp)
	err := c.cc.Invoke(ctx, "/authorization.RPCAuthorization/AuthSignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCAuthorizationServer is the server API for RPCAuthorization service.
type RPCAuthorizationServer interface {
	AuthSignIn(context.Context, *AuthSingInRequest) (*types.Empty, error)
	AuthSignUp(context.Context, *AuthSingUpRequest) (*AuthSingUpRsp, error)
}

// UnimplementedRPCAuthorizationServer can be embedded to have forward compatible implementations.
type UnimplementedRPCAuthorizationServer struct {
}

func (*UnimplementedRPCAuthorizationServer) AuthSignIn(ctx context.Context, req *AuthSingInRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSignIn not implemented")
}
func (*UnimplementedRPCAuthorizationServer) AuthSignUp(ctx context.Context, req *AuthSingUpRequest) (*AuthSingUpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSignUp not implemented")
}

func RegisterRPCAuthorizationServer(s *grpc.Server, srv RPCAuthorizationServer) {
	s.RegisterService(&_RPCAuthorization_serviceDesc, srv)
}

func _RPCAuthorization_AuthSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSingInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).AuthSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.RPCAuthorization/AuthSignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).AuthSignIn(ctx, req.(*AuthSingInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAuthorization_AuthSignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSingUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).AuthSignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorization.RPCAuthorization/AuthSignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).AuthSignUp(ctx, req.(*AuthSingUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCAuthorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authorization.RPCAuthorization",
	HandlerType: (*RPCAuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthSignIn",
			Handler:    _RPCAuthorization_AuthSignIn_Handler,
		},
		{
			MethodName: "AuthSignUp",
			Handler:    _RPCAuthorization_AuthSignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorization_service.proto",
}
