// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authorization_service.proto

package authorization

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthSingUpRequest struct {
	Balance              float64  `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Profile              string   `protobuf:"bytes,8,opt,name=profile,proto3" json:"profile,omitempty"`
	Gender               string   `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingUpRequest) Reset()         { *m = AuthSingUpRequest{} }
func (m *AuthSingUpRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSingUpRequest) ProtoMessage()    {}
func (*AuthSingUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{0}
}
func (m *AuthSingUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingUpRequest.Unmarshal(m, b)
}
func (m *AuthSingUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingUpRequest.Marshal(b, m, deterministic)
}
func (m *AuthSingUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingUpRequest.Merge(m, src)
}
func (m *AuthSingUpRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSingUpRequest.Size(m)
}
func (m *AuthSingUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingUpRequest proto.InternalMessageInfo

func (m *AuthSingUpRequest) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *AuthSingUpRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthSingUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AuthSingUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AuthSingUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthSingUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthSingUpRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuthSingUpRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *AuthSingUpRequest) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

type AuthSingInRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingInRequest) Reset()         { *m = AuthSingInRequest{} }
func (m *AuthSingInRequest) String() string { return proto.CompactTextString(m) }
func (*AuthSingInRequest) ProtoMessage()    {}
func (*AuthSingInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{1}
}
func (m *AuthSingInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingInRequest.Unmarshal(m, b)
}
func (m *AuthSingInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingInRequest.Marshal(b, m, deterministic)
}
func (m *AuthSingInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingInRequest.Merge(m, src)
}
func (m *AuthSingInRequest) XXX_Size() int {
	return xxx_messageInfo_AuthSingInRequest.Size(m)
}
func (m *AuthSingInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingInRequest proto.InternalMessageInfo

func (m *AuthSingInRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthSingInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthSingUpRsp struct {
	Data                 int64    `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingUpRsp) Reset()         { *m = AuthSingUpRsp{} }
func (m *AuthSingUpRsp) String() string { return proto.CompactTextString(m) }
func (*AuthSingUpRsp) ProtoMessage()    {}
func (*AuthSingUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{2}
}
func (m *AuthSingUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingUpRsp.Unmarshal(m, b)
}
func (m *AuthSingUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingUpRsp.Marshal(b, m, deterministic)
}
func (m *AuthSingUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingUpRsp.Merge(m, src)
}
func (m *AuthSingUpRsp) XXX_Size() int {
	return xxx_messageInfo_AuthSingUpRsp.Size(m)
}
func (m *AuthSingUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingUpRsp proto.InternalMessageInfo

func (m *AuthSingUpRsp) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type AuthSingInRsp struct {
	Data                 int64    `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthSingInRsp) Reset()         { *m = AuthSingInRsp{} }
func (m *AuthSingInRsp) String() string { return proto.CompactTextString(m) }
func (*AuthSingInRsp) ProtoMessage()    {}
func (*AuthSingInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27dc8f5aa0b42d7, []int{3}
}
func (m *AuthSingInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthSingInRsp.Unmarshal(m, b)
}
func (m *AuthSingInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthSingInRsp.Marshal(b, m, deterministic)
}
func (m *AuthSingInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthSingInRsp.Merge(m, src)
}
func (m *AuthSingInRsp) XXX_Size() int {
	return xxx_messageInfo_AuthSingInRsp.Size(m)
}
func (m *AuthSingInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthSingInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthSingInRsp proto.InternalMessageInfo

func (m *AuthSingInRsp) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthSingUpRequest)(nil), "mtproto.AuthSingUpRequest")
	proto.RegisterType((*AuthSingInRequest)(nil), "mtproto.AuthSingInRequest")
	proto.RegisterType((*AuthSingUpRsp)(nil), "mtproto.AuthSingUpRsp")
	proto.RegisterType((*AuthSingInRsp)(nil), "mtproto.AuthSingInRsp")
}

func init() { proto.RegisterFile("authorization_service.proto", fileDescriptor_e27dc8f5aa0b42d7) }

var fileDescriptor_e27dc8f5aa0b42d7 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xd9, 0x7e, 0x67, 0xa4, 0xa0, 0x8b, 0x96, 0x25, 0x45, 0x28, 0xf5, 0xd2, 0x53, 0x0f,
	0xfa, 0x04, 0xad, 0x20, 0x16, 0xa4, 0x84, 0x94, 0x5e, 0x7a, 0x29, 0xdb, 0x76, 0xdb, 0x06, 0xf2,
	0xb1, 0xee, 0x6e, 0x14, 0x7d, 0x12, 0x9f, 0x56, 0x64, 0x27, 0x8d, 0x26, 0x1a, 0x6f, 0x33, 0xf3,
	0x9b, 0x19, 0xfe, 0xff, 0x9d, 0x85, 0x3e, 0x4f, 0xcd, 0x31, 0x51, 0xc1, 0x3b, 0x37, 0x41, 0x12,
	0xaf, 0xb5, 0x50, 0x2f, 0xc1, 0x56, 0x8c, 0xa5, 0x4a, 0x4c, 0x42, 0xdb, 0x91, 0xc1, 0x60, 0xf8,
	0x49, 0xe0, 0x62, 0x92, 0x9a, 0xe3, 0x22, 0x88, 0x0f, 0x4b, 0xe9, 0x8b, 0xe7, 0x54, 0x68, 0x43,
	0x19, 0xb4, 0x37, 0x3c, 0xe4, 0xf1, 0x56, 0x30, 0x32, 0x20, 0x23, 0xe2, 0xe7, 0x29, 0xed, 0x83,
	0x93, 0x6a, 0xa1, 0xd6, 0x31, 0x8f, 0x04, 0xab, 0x0d, 0xc8, 0xc8, 0xf1, 0x3b, 0xb6, 0x30, 0xe7,
	0x91, 0xa0, 0xd7, 0x00, 0xfb, 0x40, 0x69, 0x93, 0xd1, 0x3a, 0x52, 0x07, 0x2b, 0x88, 0xfb, 0xe0,
	0x84, 0x3c, 0xa7, 0x8d, 0x6c, 0xd6, 0x16, 0x10, 0xba, 0xd0, 0x91, 0x5c, 0xeb, 0xd7, 0x44, 0xed,
	0x58, 0x33, 0x63, 0x79, 0x4e, 0x2f, 0xa1, 0x29, 0x22, 0x1e, 0x84, 0xac, 0x85, 0x20, 0x4b, 0x28,
	0x85, 0x86, 0x79, 0x93, 0x82, 0xb5, 0xb1, 0x88, 0xb1, 0x15, 0x2e, 0x55, 0xb2, 0x0f, 0x42, 0xc1,
	0x3a, 0x58, 0xce, 0x53, 0xda, 0x83, 0xd6, 0x41, 0xc4, 0x3b, 0xa1, 0x98, 0x83, 0xe0, 0x94, 0x0d,
	0x9f, 0x7e, 0xfc, 0xcf, 0xe2, 0xdc, 0x7f, 0xc9, 0x25, 0xf9, 0xe5, 0xb2, 0xa8, 0xb4, 0x56, 0x56,
	0x3a, 0xbc, 0x81, 0x6e, 0xe1, 0x35, 0xb5, 0xb4, 0x22, 0x77, 0xdc, 0x70, 0x5c, 0x52, 0xf7, 0x31,
	0x2e, 0x36, 0xcd, 0xe2, 0x7f, 0x9a, 0x6e, 0x3f, 0x08, 0x9c, 0xfb, 0xde, 0xfd, 0xa4, 0x78, 0x44,
	0x3a, 0x81, 0x33, 0x7b, 0xd5, 0xb5, 0xb6, 0xa3, 0x73, 0xea, 0x8e, 0x4f, 0x67, 0x1c, 0xff, 0xb1,
	0xe0, 0xf6, 0xaa, 0x98, 0x96, 0xa5, 0x15, 0x4b, 0xaf, 0x62, 0xc5, 0xf7, 0x2f, 0xa8, 0x58, 0x81,
	0x9e, 0xa6, 0x0f, 0x70, 0x55, 0xf9, 0xb7, 0xa6, 0xee, 0xca, 0xb3, 0xed, 0x25, 0xcd, 0x8b, 0x8c,
	0x3d, 0xd6, 0x3c, 0xb2, 0xea, 0x96, 0xc6, 0x36, 0x2d, 0x5c, 0x7e, 0xf7, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xb8, 0xca, 0xaf, 0x00, 0xaa, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCAuthorizationClient is the client API for RPCAuthorization service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCAuthorizationClient interface {
	AuthSingIN(ctx context.Context, in *AuthSingInRequest, opts ...grpc.CallOption) (*AuthSingInRsp, error)
	AuthSingUP(ctx context.Context, in *AuthSingUpRequest, opts ...grpc.CallOption) (*AuthSingUpRsp, error)
}

type rPCAuthorizationClient struct {
	cc *grpc.ClientConn
}

func NewRPCAuthorizationClient(cc *grpc.ClientConn) RPCAuthorizationClient {
	return &rPCAuthorizationClient{cc}
}

func (c *rPCAuthorizationClient) AuthSingIN(ctx context.Context, in *AuthSingInRequest, opts ...grpc.CallOption) (*AuthSingInRsp, error) {
	out := new(AuthSingInRsp)
	err := c.cc.Invoke(ctx, "/mtproto.RPCAuthorization/auth_singIN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAuthorizationClient) AuthSingUP(ctx context.Context, in *AuthSingUpRequest, opts ...grpc.CallOption) (*AuthSingUpRsp, error) {
	out := new(AuthSingUpRsp)
	err := c.cc.Invoke(ctx, "/mtproto.RPCAuthorization/auth_singUP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCAuthorizationServer is the server API for RPCAuthorization service.
type RPCAuthorizationServer interface {
	AuthSingIN(context.Context, *AuthSingInRequest) (*AuthSingInRsp, error)
	AuthSingUP(context.Context, *AuthSingUpRequest) (*AuthSingUpRsp, error)
}

// UnimplementedRPCAuthorizationServer can be embedded to have forward compatible implementations.
type UnimplementedRPCAuthorizationServer struct {
}

func (*UnimplementedRPCAuthorizationServer) AuthSingIN(ctx context.Context, req *AuthSingInRequest) (*AuthSingInRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSingIN not implemented")
}
func (*UnimplementedRPCAuthorizationServer) AuthSingUP(ctx context.Context, req *AuthSingUpRequest) (*AuthSingUpRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthSingUP not implemented")
}

func RegisterRPCAuthorizationServer(s *grpc.Server, srv RPCAuthorizationServer) {
	s.RegisterService(&_RPCAuthorization_serviceDesc, srv)
}

func _RPCAuthorization_AuthSingIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSingInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).AuthSingIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCAuthorization/AuthSingIN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).AuthSingIN(ctx, req.(*AuthSingInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAuthorization_AuthSingUP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthSingUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAuthorizationServer).AuthSingUP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtproto.RPCAuthorization/AuthSingUP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAuthorizationServer).AuthSingUP(ctx, req.(*AuthSingUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCAuthorization_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCAuthorization",
	HandlerType: (*RPCAuthorizationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "auth_singIN",
			Handler:    _RPCAuthorization_AuthSingIN_Handler,
		},
		{
			MethodName: "auth_singUP",
			Handler:    _RPCAuthorization_AuthSingUP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorization_service.proto",
}
