// Code generated by goctl. DO NOT EDIT.
// Source: accounts.proto

package service

import (
	"context"

	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/service/biz/accounts/accounts"
	"gitlab.com/merehead/elloapp/backend/elloapp_tg_backend/app/service/biz/accounts/internal/core"
)

func (s *Service) AccountsDelete(ctx context.Context, in *accounts.DeleteAccountReq) (*accounts.DeleteAccountResp, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_delete - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.AccountsDelete(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_delete - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsChangePassword(ctx context.Context, in *accounts.ChangeAccountPasswordReq) (*accounts.ChangeAccountPasswordResp, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_changePassword - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.AccountsChangePassword(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_changePassword - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsChangeEmail(ctx context.Context, in *accounts.ChangeAccountEmailReq) (*accounts.ChangeAccountEmailResp, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_changeEmail - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.AccountsChangeEmail(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_changeEmail - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsChangeProfile(ctx context.Context, in *accounts.ChangeAccountInfoReq) (*accounts.ChangeAccountInfoResp, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_changeProfile - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.AccountsChangeProfile(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_changeProfile - reply: %+v", r)
	return r, err
}

func (s *Service) AccountsForgotPassword(ctx context.Context, in *accounts.ForgotAccountPassReq) (*accounts.ForgotAccountPassResp, error) {
	c := core.NewAccounts(ctx, s.svcCtx)

	c.Logger.Debugf("accounts.accounts_forgotPassword - metadata: %s, request: %s", c.MD.DebugString(), in.String())
	r, err := c.AccountsForgotPassword(in)
	if err != nil {
		return nil, err
	}

	c.Logger.Debugf("accounts.accounts_forgotPassword - reply: %+v", r)
	return r, err
}
