// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DeleteAccountReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountReq) Reset()         { *m = DeleteAccountReq{} }
func (m *DeleteAccountReq) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountReq) ProtoMessage()    {}
func (*DeleteAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}
func (m *DeleteAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountReq.Unmarshal(m, b)
}
func (m *DeleteAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountReq.Marshal(b, m, deterministic)
}
func (m *DeleteAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountReq.Merge(m, src)
}
func (m *DeleteAccountReq) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountReq.Size(m)
}
func (m *DeleteAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountReq proto.InternalMessageInfo

func (m *DeleteAccountReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteAccountResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResp) Reset()         { *m = DeleteAccountResp{} }
func (m *DeleteAccountResp) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResp) ProtoMessage()    {}
func (*DeleteAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}
func (m *DeleteAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResp.Unmarshal(m, b)
}
func (m *DeleteAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResp.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResp.Merge(m, src)
}
func (m *DeleteAccountResp) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResp.Size(m)
}
func (m *DeleteAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResp proto.InternalMessageInfo

func (m *DeleteAccountResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DeleteAccountResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChangeAccountPasswordReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PrevPass             string   `protobuf:"bytes,2,opt,name=prev_pass,json=prevPass,proto3" json:"prev_pass,omitempty"`
	NewPass              string   `protobuf:"bytes,3,opt,name=new_pass,json=newPass,proto3" json:"new_pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountPasswordReq) Reset()         { *m = ChangeAccountPasswordReq{} }
func (m *ChangeAccountPasswordReq) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountPasswordReq) ProtoMessage()    {}
func (*ChangeAccountPasswordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}
func (m *ChangeAccountPasswordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountPasswordReq.Unmarshal(m, b)
}
func (m *ChangeAccountPasswordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountPasswordReq.Marshal(b, m, deterministic)
}
func (m *ChangeAccountPasswordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountPasswordReq.Merge(m, src)
}
func (m *ChangeAccountPasswordReq) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountPasswordReq.Size(m)
}
func (m *ChangeAccountPasswordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountPasswordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountPasswordReq proto.InternalMessageInfo

func (m *ChangeAccountPasswordReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangeAccountPasswordReq) GetPrevPass() string {
	if m != nil {
		return m.PrevPass
	}
	return ""
}

func (m *ChangeAccountPasswordReq) GetNewPass() string {
	if m != nil {
		return m.NewPass
	}
	return ""
}

type ChangeAccountPasswordResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationExpire   int64    `protobuf:"varint,4,opt,name=confirmation_expire,json=confirmationExpire,proto3" json:"confirmation_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountPasswordResp) Reset()         { *m = ChangeAccountPasswordResp{} }
func (m *ChangeAccountPasswordResp) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountPasswordResp) ProtoMessage()    {}
func (*ChangeAccountPasswordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}
func (m *ChangeAccountPasswordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountPasswordResp.Unmarshal(m, b)
}
func (m *ChangeAccountPasswordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountPasswordResp.Marshal(b, m, deterministic)
}
func (m *ChangeAccountPasswordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountPasswordResp.Merge(m, src)
}
func (m *ChangeAccountPasswordResp) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountPasswordResp.Size(m)
}
func (m *ChangeAccountPasswordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountPasswordResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountPasswordResp proto.InternalMessageInfo

func (m *ChangeAccountPasswordResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ChangeAccountPasswordResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeAccountPasswordResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangeAccountPasswordResp) GetConfirmationExpire() int64 {
	if m != nil {
		return m.ConfirmationExpire
	}
	return 0
}

type ChangeAccountEmailReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountEmailReq) Reset()         { *m = ChangeAccountEmailReq{} }
func (m *ChangeAccountEmailReq) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountEmailReq) ProtoMessage()    {}
func (*ChangeAccountEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}
func (m *ChangeAccountEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountEmailReq.Unmarshal(m, b)
}
func (m *ChangeAccountEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountEmailReq.Marshal(b, m, deterministic)
}
func (m *ChangeAccountEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountEmailReq.Merge(m, src)
}
func (m *ChangeAccountEmailReq) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountEmailReq.Size(m)
}
func (m *ChangeAccountEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountEmailReq proto.InternalMessageInfo

func (m *ChangeAccountEmailReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangeAccountEmailReq) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type ChangeAccountEmailResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationExpire   int64    `protobuf:"varint,4,opt,name=confirmation_expire,json=confirmationExpire,proto3" json:"confirmation_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountEmailResp) Reset()         { *m = ChangeAccountEmailResp{} }
func (m *ChangeAccountEmailResp) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountEmailResp) ProtoMessage()    {}
func (*ChangeAccountEmailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}
func (m *ChangeAccountEmailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountEmailResp.Unmarshal(m, b)
}
func (m *ChangeAccountEmailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountEmailResp.Marshal(b, m, deterministic)
}
func (m *ChangeAccountEmailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountEmailResp.Merge(m, src)
}
func (m *ChangeAccountEmailResp) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountEmailResp.Size(m)
}
func (m *ChangeAccountEmailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountEmailResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountEmailResp proto.InternalMessageInfo

func (m *ChangeAccountEmailResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ChangeAccountEmailResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChangeAccountEmailResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangeAccountEmailResp) GetConfirmationExpire() int64 {
	if m != nil {
		return m.ConfirmationExpire
	}
	return 0
}

type ChangeAccountInfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday             string   `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	CountryCode          string   `protobuf:"bytes,8,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountInfoReq) Reset()         { *m = ChangeAccountInfoReq{} }
func (m *ChangeAccountInfoReq) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountInfoReq) ProtoMessage()    {}
func (*ChangeAccountInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}
func (m *ChangeAccountInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountInfoReq.Unmarshal(m, b)
}
func (m *ChangeAccountInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountInfoReq.Marshal(b, m, deterministic)
}
func (m *ChangeAccountInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountInfoReq.Merge(m, src)
}
func (m *ChangeAccountInfoReq) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountInfoReq.Size(m)
}
func (m *ChangeAccountInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountInfoReq proto.InternalMessageInfo

func (m *ChangeAccountInfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangeAccountInfoReq) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ChangeAccountInfoReq) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ChangeAccountInfoReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ChangeAccountInfoReq) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *ChangeAccountInfoReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *ChangeAccountInfoReq) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *ChangeAccountInfoReq) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

type ChangeAccountInfoResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAccountInfoResp) Reset()         { *m = ChangeAccountInfoResp{} }
func (m *ChangeAccountInfoResp) String() string { return proto.CompactTextString(m) }
func (*ChangeAccountInfoResp) ProtoMessage()    {}
func (*ChangeAccountInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}
func (m *ChangeAccountInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAccountInfoResp.Unmarshal(m, b)
}
func (m *ChangeAccountInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAccountInfoResp.Marshal(b, m, deterministic)
}
func (m *ChangeAccountInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAccountInfoResp.Merge(m, src)
}
func (m *ChangeAccountInfoResp) XXX_Size() int {
	return xxx_messageInfo_ChangeAccountInfoResp.Size(m)
}
func (m *ChangeAccountInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAccountInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAccountInfoResp proto.InternalMessageInfo

func (m *ChangeAccountInfoResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ChangeAccountInfoResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ConfirmationSendReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationSendReq) Reset()         { *m = ConfirmationSendReq{} }
func (m *ConfirmationSendReq) String() string { return proto.CompactTextString(m) }
func (*ConfirmationSendReq) ProtoMessage()    {}
func (*ConfirmationSendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}
func (m *ConfirmationSendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationSendReq.Unmarshal(m, b)
}
func (m *ConfirmationSendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationSendReq.Marshal(b, m, deterministic)
}
func (m *ConfirmationSendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationSendReq.Merge(m, src)
}
func (m *ConfirmationSendReq) XXX_Size() int {
	return xxx_messageInfo_ConfirmationSendReq.Size(m)
}
func (m *ConfirmationSendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationSendReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationSendReq proto.InternalMessageInfo

func (m *ConfirmationSendReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ConfirmationSendResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationExpire   int64    `protobuf:"varint,4,opt,name=confirmation_expire,json=confirmationExpire,proto3" json:"confirmation_expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationSendResp) Reset()         { *m = ConfirmationSendResp{} }
func (m *ConfirmationSendResp) String() string { return proto.CompactTextString(m) }
func (*ConfirmationSendResp) ProtoMessage()    {}
func (*ConfirmationSendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}
func (m *ConfirmationSendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationSendResp.Unmarshal(m, b)
}
func (m *ConfirmationSendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationSendResp.Marshal(b, m, deterministic)
}
func (m *ConfirmationSendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationSendResp.Merge(m, src)
}
func (m *ConfirmationSendResp) XXX_Size() int {
	return xxx_messageInfo_ConfirmationSendResp.Size(m)
}
func (m *ConfirmationSendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationSendResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationSendResp proto.InternalMessageInfo

func (m *ConfirmationSendResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ConfirmationSendResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ConfirmationSendResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmationSendResp) GetConfirmationExpire() int64 {
	if m != nil {
		return m.ConfirmationExpire
	}
	return 0
}

type ConfirmationConfirmReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationConfirmReq) Reset()         { *m = ConfirmationConfirmReq{} }
func (m *ConfirmationConfirmReq) String() string { return proto.CompactTextString(m) }
func (*ConfirmationConfirmReq) ProtoMessage()    {}
func (*ConfirmationConfirmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}
func (m *ConfirmationConfirmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationConfirmReq.Unmarshal(m, b)
}
func (m *ConfirmationConfirmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationConfirmReq.Marshal(b, m, deterministic)
}
func (m *ConfirmationConfirmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationConfirmReq.Merge(m, src)
}
func (m *ConfirmationConfirmReq) XXX_Size() int {
	return xxx_messageInfo_ConfirmationConfirmReq.Size(m)
}
func (m *ConfirmationConfirmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationConfirmReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationConfirmReq proto.InternalMessageInfo

func (m *ConfirmationConfirmReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmationConfirmReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ConfirmationConfirmResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationConfirmResp) Reset()         { *m = ConfirmationConfirmResp{} }
func (m *ConfirmationConfirmResp) String() string { return proto.CompactTextString(m) }
func (*ConfirmationConfirmResp) ProtoMessage()    {}
func (*ConfirmationConfirmResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}
func (m *ConfirmationConfirmResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationConfirmResp.Unmarshal(m, b)
}
func (m *ConfirmationConfirmResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationConfirmResp.Marshal(b, m, deterministic)
}
func (m *ConfirmationConfirmResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationConfirmResp.Merge(m, src)
}
func (m *ConfirmationConfirmResp) XXX_Size() int {
	return xxx_messageInfo_ConfirmationConfirmResp.Size(m)
}
func (m *ConfirmationConfirmResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationConfirmResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationConfirmResp proto.InternalMessageInfo

func (m *ConfirmationConfirmResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ConfirmationConfirmResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteAccountReq)(nil), "account.DeleteAccountReq")
	proto.RegisterType((*DeleteAccountResp)(nil), "account.DeleteAccountResp")
	proto.RegisterType((*ChangeAccountPasswordReq)(nil), "account.ChangeAccountPasswordReq")
	proto.RegisterType((*ChangeAccountPasswordResp)(nil), "account.ChangeAccountPasswordResp")
	proto.RegisterType((*ChangeAccountEmailReq)(nil), "account.ChangeAccountEmailReq")
	proto.RegisterType((*ChangeAccountEmailResp)(nil), "account.ChangeAccountEmailResp")
	proto.RegisterType((*ChangeAccountInfoReq)(nil), "account.ChangeAccountInfoReq")
	proto.RegisterType((*ChangeAccountInfoResp)(nil), "account.ChangeAccountInfoResp")
	proto.RegisterType((*ConfirmationSendReq)(nil), "account.ConfirmationSendReq")
	proto.RegisterType((*ConfirmationSendResp)(nil), "account.ConfirmationSendResp")
	proto.RegisterType((*ConfirmationConfirmReq)(nil), "account.ConfirmationConfirmReq")
	proto.RegisterType((*ConfirmationConfirmResp)(nil), "account.ConfirmationConfirmResp")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x5d, 0x6e, 0xda, 0x40,
	0x10, 0x96, 0x03, 0x01, 0x33, 0xfd, 0x4b, 0x07, 0x42, 0x8c, 0x53, 0x12, 0xe2, 0xa7, 0x48, 0x91,
	0x52, 0xa9, 0xed, 0x05, 0x0a, 0x45, 0x2d, 0xaa, 0x5a, 0x21, 0x22, 0xb5, 0x52, 0x5e, 0xdc, 0xc5,
	0x5e, 0x88, 0x55, 0xb0, 0xdd, 0x5d, 0x13, 0x9a, 0x53, 0x54, 0x95, 0x7a, 0x81, 0x1e, 0xb1, 0x37,
	0xa8, 0x76, 0xbd, 0x4b, 0x80, 0x18, 0x47, 0xe2, 0x25, 0x6f, 0x3b, 0xf3, 0xcd, 0x7c, 0xf3, 0xb7,
	0x3b, 0x0b, 0x4f, 0x88, 0xe7, 0x45, 0xb3, 0x30, 0x39, 0x8f, 0x59, 0x94, 0x44, 0x58, 0x56, 0xa2,
	0x73, 0x06, 0x7b, 0xef, 0xe8, 0x84, 0x26, 0xf4, 0x6d, 0xaa, 0x18, 0xd0, 0x1f, 0x78, 0x00, 0xe5,
	0x19, 0xa7, 0xcc, 0x0d, 0x7c, 0xcb, 0x68, 0x19, 0xa7, 0x85, 0x41, 0x49, 0x88, 0x3d, 0xdf, 0xe9,
	0xc2, 0xf3, 0x35, 0x63, 0x1e, 0x63, 0x1d, 0x4a, 0x3c, 0x21, 0xc9, 0x8c, 0x4b, 0x63, 0x73, 0xa0,
	0x24, 0xb4, 0xa0, 0x3c, 0xa5, 0x9c, 0x93, 0x31, 0xb5, 0x76, 0x5a, 0xc6, 0x69, 0x65, 0xa0, 0x45,
	0xe7, 0x3b, 0x58, 0x9d, 0x2b, 0x12, 0x8e, 0x35, 0x4d, 0x9f, 0x70, 0x3e, 0x8f, 0x98, 0x9f, 0x17,
	0x1b, 0x0f, 0xa1, 0x12, 0x33, 0x7a, 0xed, 0xc6, 0x84, 0x73, 0x45, 0x68, 0x0a, 0x85, 0x70, 0xc6,
	0x06, 0x98, 0x21, 0x9d, 0xa7, 0x58, 0x21, 0x0d, 0x16, 0xd2, 0xb9, 0x80, 0x9c, 0x3f, 0x06, 0x34,
	0x36, 0x44, 0xdb, 0x26, 0x79, 0xac, 0xc1, 0x2e, 0x9d, 0x92, 0x60, 0xa2, 0xe2, 0xa4, 0x02, 0xbe,
	0x84, 0xaa, 0x17, 0x85, 0xa3, 0x80, 0x4d, 0x49, 0x12, 0x44, 0xa1, 0x4b, 0x7f, 0xc6, 0x01, 0xa3,
	0x56, 0x51, 0x96, 0x80, 0xcb, 0x50, 0x57, 0x22, 0xce, 0x27, 0xd8, 0x5f, 0xc9, 0xaa, 0x2b, 0x68,
	0xee, 0x6b, 0x80, 0xa8, 0x31, 0x0d, 0xae, 0x1a, 0x10, 0xd2, 0xb9, 0x74, 0x74, 0x7e, 0x1b, 0x50,
	0xcf, 0xe2, 0x7b, 0xc8, 0x12, 0xff, 0x19, 0x50, 0x5b, 0xc9, 0xa9, 0x17, 0x8e, 0xa2, 0xdc, 0x12,
	0x9b, 0x00, 0xa3, 0x80, 0xf1, 0xc4, 0x0d, 0xc9, 0x54, 0x67, 0x55, 0x91, 0x9a, 0xcf, 0x64, 0x4a,
	0x45, 0x07, 0x26, 0x44, 0xa3, 0x69, 0x6e, 0xa6, 0x50, 0x68, 0x50, 0x92, 0x4a, 0xb0, 0x98, 0x82,
	0x42, 0x21, 0xc1, 0x3d, 0x28, 0x0c, 0x83, 0xc8, 0xda, 0x95, 0x6a, 0x71, 0x14, 0x5d, 0x19, 0xd3,
	0xd0, 0xa7, 0xcc, 0x2a, 0x49, 0xa5, 0x92, 0xd0, 0x06, 0x73, 0x18, 0xb0, 0xe4, 0xca, 0x27, 0x37,
	0x56, 0x39, 0x65, 0xd1, 0x32, 0x9e, 0xc0, 0x63, 0x59, 0x07, 0xbb, 0x71, 0xbd, 0xc8, 0xa7, 0x96,
	0x29, 0xf1, 0x47, 0x4a, 0xd7, 0x89, 0x7c, 0xea, 0xf4, 0xd6, 0xc6, 0x9a, 0x96, 0xbc, 0xd5, 0x2b,
	0x39, 0x83, 0x6a, 0x67, 0xa9, 0xa9, 0x17, 0x34, 0x94, 0x0f, 0x64, 0x31, 0x1c, 0x63, 0x69, 0x38,
	0xce, 0x2f, 0xd1, 0xeb, 0x3b, 0xd6, 0x0f, 0x39, 0xfd, 0x36, 0xd4, 0x97, 0x13, 0x52, 0xe7, 0x8d,
	0x15, 0x20, 0x42, 0x51, 0x36, 0x35, 0xcd, 0x46, 0x9e, 0x9d, 0x8f, 0x70, 0x90, 0xc9, 0xb1, 0x4d,
	0x5d, 0xaf, 0xfe, 0x16, 0x01, 0x06, 0xfd, 0x8e, 0x1a, 0x0c, 0xbe, 0x87, 0xa7, 0x6a, 0x07, 0xba,
	0xbe, 0xdc, 0x69, 0xd8, 0x38, 0xd7, 0x3b, 0x72, 0x7d, 0x23, 0xda, 0xf6, 0x26, 0x88, 0xc7, 0xe8,
	0x42, 0x5d, 0x13, 0x79, 0x72, 0xf4, 0x7a, 0xc1, 0xe0, 0xc9, 0xc2, 0x6b, 0xd3, 0xba, 0xb3, 0x9d,
	0xfb, 0x4c, 0x78, 0x8c, 0x5f, 0xa0, 0xba, 0x1a, 0x40, 0xbe, 0x6d, 0x3c, 0xca, 0x76, 0xd5, 0x8b,
	0xc4, 0x3e, 0xce, 0xc5, 0x25, 0xef, 0xfe, 0x5a, 0xe2, 0x2c, 0x1a, 0x05, 0x13, 0x8a, 0xcd, 0x6c,
	0x4f, 0xf5, 0x7c, 0xed, 0xa3, 0x3c, 0x98, 0xc7, 0xf8, 0x15, 0xac, 0x05, 0xef, 0xda, 0x95, 0xc4,
	0x17, 0xb7, 0xbe, 0x77, 0xef, 0xb6, 0xdd, 0xcc, 0x41, 0x79, 0x8c, 0xdf, 0xe0, 0x30, 0x8b, 0x58,
	0xd9, 0xe2, 0x71, 0xa6, 0xf7, 0xed, 0xc5, 0xb3, 0x5b, 0xf9, 0x06, 0x3c, 0x6e, 0xbf, 0x81, 0x67,
	0x3a, 0x02, 0xa7, 0xec, 0x3a, 0xf0, 0x68, 0xbb, 0x76, 0xd9, 0x17, 0x3f, 0xa6, 0x2a, 0xf2, 0x22,
	0xd5, 0x7e, 0xd8, 0xe9, 0x1b, 0x97, 0xfa, 0x0f, 0x1d, 0x96, 0xe4, 0x9f, 0xfa, 0xfa, 0x7f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x68, 0x26, 0x6a, 0x82, 0x64, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCAccountClient is the client API for RPCAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCAccountClient interface {
	AccountDelete(ctx context.Context, in *DeleteAccountReq, opts ...grpc.CallOption) (*DeleteAccountResp, error)
	AccountChangePassword(ctx context.Context, in *ChangeAccountPasswordReq, opts ...grpc.CallOption) (*ChangeAccountPasswordResp, error)
	AccountChangeEmail(ctx context.Context, in *ChangeAccountEmailReq, opts ...grpc.CallOption) (*ChangeAccountEmailResp, error)
	AccountChangeProfile(ctx context.Context, in *ChangeAccountInfoReq, opts ...grpc.CallOption) (*ChangeAccountInfoResp, error)
	AccountConfirmationSend(ctx context.Context, in *ConfirmationSendReq, opts ...grpc.CallOption) (*ConfirmationSendResp, error)
	AccountConfirmationConfirm(ctx context.Context, in *ConfirmationConfirmReq, opts ...grpc.CallOption) (*ConfirmationConfirmResp, error)
}

type rPCAccountClient struct {
	cc *grpc.ClientConn
}

func NewRPCAccountClient(cc *grpc.ClientConn) RPCAccountClient {
	return &rPCAccountClient{cc}
}

func (c *rPCAccountClient) AccountDelete(ctx context.Context, in *DeleteAccountReq, opts ...grpc.CallOption) (*DeleteAccountResp, error) {
	out := new(DeleteAccountResp)
	err := c.cc.Invoke(ctx, "/account.RPCAccount/account_delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAccountClient) AccountChangePassword(ctx context.Context, in *ChangeAccountPasswordReq, opts ...grpc.CallOption) (*ChangeAccountPasswordResp, error) {
	out := new(ChangeAccountPasswordResp)
	err := c.cc.Invoke(ctx, "/account.RPCAccount/account_changePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAccountClient) AccountChangeEmail(ctx context.Context, in *ChangeAccountEmailReq, opts ...grpc.CallOption) (*ChangeAccountEmailResp, error) {
	out := new(ChangeAccountEmailResp)
	err := c.cc.Invoke(ctx, "/account.RPCAccount/account_changeEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAccountClient) AccountChangeProfile(ctx context.Context, in *ChangeAccountInfoReq, opts ...grpc.CallOption) (*ChangeAccountInfoResp, error) {
	out := new(ChangeAccountInfoResp)
	err := c.cc.Invoke(ctx, "/account.RPCAccount/account_changeProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAccountClient) AccountConfirmationSend(ctx context.Context, in *ConfirmationSendReq, opts ...grpc.CallOption) (*ConfirmationSendResp, error) {
	out := new(ConfirmationSendResp)
	err := c.cc.Invoke(ctx, "/account.RPCAccount/account_confirmationSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCAccountClient) AccountConfirmationConfirm(ctx context.Context, in *ConfirmationConfirmReq, opts ...grpc.CallOption) (*ConfirmationConfirmResp, error) {
	out := new(ConfirmationConfirmResp)
	err := c.cc.Invoke(ctx, "/account.RPCAccount/account_confirmationConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCAccountServer is the server API for RPCAccount service.
type RPCAccountServer interface {
	AccountDelete(context.Context, *DeleteAccountReq) (*DeleteAccountResp, error)
	AccountChangePassword(context.Context, *ChangeAccountPasswordReq) (*ChangeAccountPasswordResp, error)
	AccountChangeEmail(context.Context, *ChangeAccountEmailReq) (*ChangeAccountEmailResp, error)
	AccountChangeProfile(context.Context, *ChangeAccountInfoReq) (*ChangeAccountInfoResp, error)
	AccountConfirmationSend(context.Context, *ConfirmationSendReq) (*ConfirmationSendResp, error)
	AccountConfirmationConfirm(context.Context, *ConfirmationConfirmReq) (*ConfirmationConfirmResp, error)
}

// UnimplementedRPCAccountServer can be embedded to have forward compatible implementations.
type UnimplementedRPCAccountServer struct {
}

func (*UnimplementedRPCAccountServer) AccountDelete(ctx context.Context, req *DeleteAccountReq) (*DeleteAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountDelete not implemented")
}
func (*UnimplementedRPCAccountServer) AccountChangePassword(ctx context.Context, req *ChangeAccountPasswordReq) (*ChangeAccountPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountChangePassword not implemented")
}
func (*UnimplementedRPCAccountServer) AccountChangeEmail(ctx context.Context, req *ChangeAccountEmailReq) (*ChangeAccountEmailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountChangeEmail not implemented")
}
func (*UnimplementedRPCAccountServer) AccountChangeProfile(ctx context.Context, req *ChangeAccountInfoReq) (*ChangeAccountInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountChangeProfile not implemented")
}
func (*UnimplementedRPCAccountServer) AccountConfirmationSend(ctx context.Context, req *ConfirmationSendReq) (*ConfirmationSendResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountConfirmationSend not implemented")
}
func (*UnimplementedRPCAccountServer) AccountConfirmationConfirm(ctx context.Context, req *ConfirmationConfirmReq) (*ConfirmationConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountConfirmationConfirm not implemented")
}

func RegisterRPCAccountServer(s *grpc.Server, srv RPCAccountServer) {
	s.RegisterService(&_RPCAccount_serviceDesc, srv)
}

func _RPCAccount_AccountDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAccountServer).AccountDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.RPCAccount/AccountDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAccountServer).AccountDelete(ctx, req.(*DeleteAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAccount_AccountChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAccountServer).AccountChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.RPCAccount/AccountChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAccountServer).AccountChangePassword(ctx, req.(*ChangeAccountPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAccount_AccountChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAccountServer).AccountChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.RPCAccount/AccountChangeEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAccountServer).AccountChangeEmail(ctx, req.(*ChangeAccountEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAccount_AccountChangeProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAccountServer).AccountChangeProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.RPCAccount/AccountChangeProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAccountServer).AccountChangeProfile(ctx, req.(*ChangeAccountInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAccount_AccountConfirmationSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAccountServer).AccountConfirmationSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.RPCAccount/AccountConfirmationSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAccountServer).AccountConfirmationSend(ctx, req.(*ConfirmationSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCAccount_AccountConfirmationConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCAccountServer).AccountConfirmationConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.RPCAccount/AccountConfirmationConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCAccountServer).AccountConfirmationConfirm(ctx, req.(*ConfirmationConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCAccount_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.RPCAccount",
	HandlerType: (*RPCAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "account_delete",
			Handler:    _RPCAccount_AccountDelete_Handler,
		},
		{
			MethodName: "account_changePassword",
			Handler:    _RPCAccount_AccountChangePassword_Handler,
		},
		{
			MethodName: "account_changeEmail",
			Handler:    _RPCAccount_AccountChangeEmail_Handler,
		},
		{
			MethodName: "account_changeProfile",
			Handler:    _RPCAccount_AccountChangeProfile_Handler,
		},
		{
			MethodName: "account_confirmationSend",
			Handler:    _RPCAccount_AccountConfirmationSend_Handler,
		},
		{
			MethodName: "account_confirmationConfirm",
			Handler:    _RPCAccount_AccountConfirmationConfirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
